#ifndef _GCN_ERROR_H_
#define _GCN_ERROR_H_

typedef enum {
	// not errors
	GCN_ERR_OK = 0,
	GCN_ERR_END_OF_CODE,

	// errors
	GCN_ERR_BUFFER_TOO_SMALL,
	GCN_ERR_CODE_TOO_SMALL,
	GCN_ERR_INVALID_ARG,
	GCN_ERR_INVALID_DST_FIELD,
	GCN_ERR_INVALID_MICROCODE,
	GCN_ERR_INVALID_OPCODE,
	GCN_ERR_INVALID_SRC_FIELD,
	GCN_ERR_INTERNAL_ERROR,
	GCN_ERR_OVERFLOW,
	GCN_ERR_RESOURCE_MISMATCH,
	GCN_ERR_SIZE_NOT_A_MULTIPLE_FOUR,
	GCN_ERR_TOO_MANY_CONSTS,
	GCN_ERR_UNIMPLEMENTED,
	GCN_ERR_UNINITIALIZED_CONTEXT,
} GcnError;

const char* gcnStrError(GcnError err);

#endif	// _GCN_ERROR_H_
