#include "gcn_types.h"

#include "u/utility.h"

const char* gcnStrMicrocode(GcnMicrocode mc) {
	switch (mc) {
	case GCN_MICROCODE_SOP1:
		return "SOP1";
	case GCN_MICROCODE_SOP2:
		return "SOP2";
	case GCN_MICROCODE_SOPC:
		return "SOPC";
	case GCN_MICROCODE_SOPK:
		return "SOPK";
	case GCN_MICROCODE_SOPP:
		return "SOPP";
	case GCN_MICROCODE_VOP1:
		return "VOP1";
	case GCN_MICROCODE_VOP2:
		return "VOP2";
	case GCN_MICROCODE_VOP3:
		return "VOP3";
	case GCN_MICROCODE_VOPC:
		return "VOPC";
	case GCN_MICROCODE_VINTRP:
		return "VINTRP";
	case GCN_MICROCODE_SMRD:
		return "SMRD";
	case GCN_MICROCODE_DS:
		return "DS";
	case GCN_MICROCODE_MUBUF:
		return "MUBUF";
	case GCN_MICROCODE_MTBUF:
		return "MTBUF";
	case GCN_MICROCODE_MIMG:
		return "MIMG";
	case GCN_MICROCODE_EXP:
		return "EXP";
	default:
		return "Invalid microcode";
	}
}

const char* gcnStrOpcodeDS(GcnOpcodeDS op) {
	switch (op) {
	case GCN_DS_ADD_U32:
		return "ds_add_u32";
	case GCN_DS_SUB_U32:
		return "ds_sub_u32";
	case GCN_DS_RSUB_U32:
		return "ds_rsub_u32";
	case GCN_DS_INC_U32:
		return "ds_inc_u32";
	case GCN_DS_DEC_U32:
		return "ds_dec_u32";
	case GCN_DS_MIN_I32:
		return "ds_min_i32";
	case GCN_DS_MAX_I32:
		return "ds_max_i32";
	case GCN_DS_MIN_U32:
		return "ds_min_u32";
	case GCN_DS_MAX_U32:
		return "ds_max_u32";
	case GCN_DS_AND_B32:
		return "ds_and_b32";
	case GCN_DS_OR_B32:
		return "ds_or_b32";
	case GCN_DS_XOR_B32:
		return "ds_xor_b32";
	case GCN_DS_MSKOR_B32:
		return "ds_mskor_b32";
	case GCN_DS_WRITE_B32:
		return "ds_write_b32";
	case GCN_DS_WRITE2_B32:
		return "ds_write2_b32";
	case GCN_DS_WRITE2ST64_B32:
		return "ds_write2st64_b32";
	case GCN_DS_CMPST_B32:
		return "ds_cmpst_b32";
	case GCN_DS_CMPST_F32:
		return "ds_cmpst_f32";
	case GCN_DS_MIN_F32:
		return "ds_min_f32";
	case GCN_DS_MAX_F32:
		return "ds_max_f32";
	case GCN_DS_NOP:
		return "ds_nop";
	case GCN_DS_GWS_SEMA_RELEASE_ALL:
		return "ds_gws_sema_release_all";
	case GCN_DS_GWS_INIT:
		return "ds_gws_init";
	case GCN_DS_GWS_SEMA_V:
		return "ds_gws_sema_v";
	case GCN_DS_GWS_SEMA_BR:
		return "ds_gws_sema_br";
	case GCN_DS_GWS_SEMA_P:
		return "ds_gws_sema_p";
	case GCN_DS_GWS_BARRIER:
		return "ds_gws_barrier";
	case GCN_DS_WRITE_B8:
		return "ds_write_b8";
	case GCN_DS_WRITE_B16:
		return "ds_write_b16";
	case GCN_DS_ADD_RTN_U32:
		return "ds_add_rtn_u32";
	case GCN_DS_SUB_RTN_U32:
		return "ds_sub_rtn_u32";
	case GCN_DS_RSUB_RTN_U32:
		return "ds_rsub_rtn_u32";
	case GCN_DS_INC_RTN_U32:
		return "ds_inc_rtn_u32";
	case GCN_DS_DEC_RTN_U32:
		return "ds_dec_rtn_u32";
	case GCN_DS_MIN_RTN_I32:
		return "ds_min_rtn_i32";
	case GCN_DS_MAX_RTN_I32:
		return "ds_max_rtn_i32";
	case GCN_DS_MIN_RTN_U32:
		return "ds_min_rtn_u32";
	case GCN_DS_MAX_RTN_U32:
		return "ds_max_rtn_u32";
	case GCN_DS_AND_RTN_B32:
		return "ds_and_rtn_b32";
	case GCN_DS_OR_RTN_B32:
		return "ds_or_rtn_b32";
	case GCN_DS_XOR_RTN_B32:
		return "ds_xor_rtn_b32";
	case GCN_DS_MSKOR_RTN_B32:
		return "ds_mskor_rtn_b32";
	case GCN_DS_WRXCHG_RTN_B32:
		return "ds_wrxchg_rtn_b32";
	case GCN_DS_WRXCHG2_RTN_B32:
		return "ds_wrxchg2_rtn_b32";
	case GCN_DS_WRXCHG2ST64_RTN_B32:
		return "ds_wrxchg2st64_rtn_b32";
	case GCN_DS_CMPST_RTN_B32:
		return "ds_cmpst_rtn_b32";
	case GCN_DS_CMPST_RTN_F32:
		return "ds_cmpst_rtn_f32";
	case GCN_DS_MIN_RTN_F32:
		return "ds_min_rtn_f32";
	case GCN_DS_MAX_RTN_F32:
		return "ds_max_rtn_f32";
	case GCN_DS_WRAP_RTN_B32:
		return "ds_wrap_rtn_b32";
	case GCN_DS_SWIZZLE_B32:
		return "ds_swizzle_b32";
	case GCN_DS_READ_B32:
		return "ds_read_b32";
	case GCN_DS_READ2_B32:
		return "ds_read2_b32";
	case GCN_DS_READ2ST64_B32:
		return "ds_read2st64_b32";
	case GCN_DS_READ_I8:
		return "ds_read_i8";
	case GCN_DS_READ_U8:
		return "ds_read_u8";
	case GCN_DS_READ_I16:
		return "ds_read_i16";
	case GCN_DS_READ_U16:
		return "ds_read_u16";
	case GCN_DS_CONSUME:
		return "ds_consume";
	case GCN_DS_APPEND:
		return "ds_append";
	case GCN_DS_ORDERED_COUNT:
		return "ds_ordered_count";
	case GCN_DS_ADD_U64:
		return "ds_add_u64";
	case GCN_DS_SUB_U64:
		return "ds_sub_u64";
	case GCN_DS_RSUB_U64:
		return "ds_rsub_u64";
	case GCN_DS_INC_U64:
		return "ds_inc_u64";
	case GCN_DS_DEC_U64:
		return "ds_dec_u64";
	case GCN_DS_MIN_I64:
		return "ds_min_i64";
	case GCN_DS_MAX_I64:
		return "ds_max_i64";
	case GCN_DS_MIN_U64:
		return "ds_min_u64";
	case GCN_DS_MAX_U64:
		return "ds_max_u64";
	case GCN_DS_AND_B64:
		return "ds_and_b64";
	case GCN_DS_OR_B64:
		return "ds_or_b64";
	case GCN_DS_XOR_B64:
		return "ds_xor_b64";
	case GCN_DS_MSKOR_B64:
		return "ds_mskor_b64";
	case GCN_DS_WRITE_B64:
		return "ds_write_b64";
	case GCN_DS_WRITE2_B64:
		return "ds_write2_b64";
	case GCN_DS_WRITE2ST64_B64:
		return "ds_write2st64_b64";
	case GCN_DS_CMPST_B64:
		return "ds_cmpst_b64";
	case GCN_DS_CMPST_F64:
		return "ds_cmpst_f64";
	case GCN_DS_MIN_F64:
		return "ds_min_f64";
	case GCN_DS_MAX_F64:
		return "ds_max_f64";
	case GCN_DS_ADD_RTN_U64:
		return "ds_add_rtn_u64";
	case GCN_DS_SUB_RTN_U64:
		return "ds_sub_rtn_u64";
	case GCN_DS_RSUB_RTN_U64:
		return "ds_rsub_rtn_u64";
	case GCN_DS_INC_RTN_U64:
		return "ds_inc_rtn_u64";
	case GCN_DS_DEC_RTN_U64:
		return "ds_dec_rtn_u64";
	case GCN_DS_MIN_RTN_I64:
		return "ds_min_rtn_i64";
	case GCN_DS_MAX_RTN_I64:
		return "ds_max_rtn_i64";
	case GCN_DS_MIN_RTN_U64:
		return "ds_min_rtn_u64";
	case GCN_DS_MAX_RTN_U64:
		return "ds_max_rtn_u64";
	case GCN_DS_AND_RTN_B64:
		return "ds_and_rtn_b64";
	case GCN_DS_OR_RTN_B64:
		return "ds_or_rtn_b64";
	case GCN_DS_XOR_RTN_B64:
		return "ds_xor_rtn_b64";
	case GCN_DS_MSKOR_RTN_B64:
		return "ds_mskor_rtn_b64";
	case GCN_DS_WRXCHG_RTN_B64:
		return "ds_wrxchg_rtn_b64";
	case GCN_DS_WRXCHG2_RTN_B64:
		return "ds_wrxchg2_rtn_b64";
	case GCN_DS_WRXCHG2ST64_RTN_B64:
		return "ds_wrxchg2st64_rtn_b64";
	case GCN_DS_CMPST_RTN_B64:
		return "ds_cmpst_rtn_b64";
	case GCN_DS_CMPST_RTN_F64:
		return "ds_cmpst_rtn_f64";
	case GCN_DS_MIN_RTN_F64:
		return "ds_min_rtn_f64";
	case GCN_DS_MAX_RTN_F64:
		return "ds_max_rtn_f64";
	case GCN_DS_READ_B64:
		return "ds_read_b64";
	case GCN_DS_READ2_B64:
		return "ds_read2_b64";
	case GCN_DS_READ2ST64_B64:
		return "ds_read2st64_b64";
	case GCN_DS_CONDXCHG32_RTN_B64:
		return "ds_condxchg32_rtn_b64";
	case GCN_DS_ADD_SRC2_U32:
		return "ds_add_src2_u32";
	case GCN_DS_SUB_SRC2_U32:
		return "ds_sub_src2_u32";
	case GCN_DS_RSUB_SRC2_U32:
		return "ds_rsub_src2_u32";
	case GCN_DS_INC_SRC2_U32:
		return "ds_inc_src2_u32";
	case GCN_DS_DEC_SRC2_U32:
		return "ds_dec_src2_u32";
	case GCN_DS_MIN_SRC2_I32:
		return "ds_min_src2_i32";
	case GCN_DS_MAX_SRC2_I32:
		return "ds_max_src2_i32";
	case GCN_DS_MIN_SRC2_U32:
		return "ds_min_src2_u32";
	case GCN_DS_MAX_SRC2_U32:
		return "ds_max_src2_u32";
	case GCN_DS_AND_SRC2_B32:
		return "ds_and_src2_b32";
	case GCN_DS_OR_SRC2_B32:
		return "ds_or_src2_b32";
	case GCN_DS_XOR_SRC2_B32:
		return "ds_xor_src2_b32";
	case GCN_DS_WRITE_SRC2_B32:
		return "ds_write_src2_b32";
	case GCN_DS_MIN_SRC2_F32:
		return "ds_min_src2_f32";
	case GCN_DS_MAX_SRC2_F32:
		return "ds_max_src2_f32";
	case GCN_DS_ADD_SRC2_U64:
		return "ds_add_src2_u64";
	case GCN_DS_SUB_SRC2_U64:
		return "ds_sub_src2_u64";
	case GCN_DS_RSUB_SRC2_U64:
		return "ds_rsub_src2_u64";
	case GCN_DS_INC_SRC2_U64:
		return "ds_inc_src2_u64";
	case GCN_DS_DEC_SRC2_U64:
		return "ds_dec_src2_u64";
	case GCN_DS_MIN_SRC2_I64:
		return "ds_min_src2_i64";
	case GCN_DS_MAX_SRC2_I64:
		return "ds_max_src2_i64";
	case GCN_DS_MIN_SRC2_U64:
		return "ds_min_src2_u64";
	case GCN_DS_MAX_SRC2_U64:
		return "ds_max_src2_u64";
	case GCN_DS_AND_SRC2_B64:
		return "ds_and_src2_b64";
	case GCN_DS_OR_SRC2_B64:
		return "ds_or_src2_b64";
	case GCN_DS_XOR_SRC2_B64:
		return "ds_xor_src2_b64";
	case GCN_DS_WRITE_SRC2_B64:
		return "ds_write_src2_b64";
	case GCN_DS_MIN_SRC2_F64:
		return "ds_min_src2_f64";
	case GCN_DS_MAX_SRC2_F64:
		return "ds_max_src2_f64";
	case GCN_DS_WRITE_B96:
		return "ds_write_b96";
	case GCN_DS_WRITE_B128:
		return "ds_write_b128";
	case GCN_DS_CONDXCHG32_RTN_B128:
		return "ds_condxchg32_rtn_b128";
	case GCN_DS_READ_B96:
		return "ds_read_b96";
	case GCN_DS_READ_B128:
		return "ds_read_b128";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeMIMG(GcnOpcodeMIMG op) {
	switch (op) {
	case GCN_IMAGE_LOAD:
		return "image_load";
	case GCN_IMAGE_LOAD_MIP:
		return "image_load_mip";
	case GCN_IMAGE_LOAD_PCK:
		return "image_load_pck";
	case GCN_IMAGE_LOAD_PCK_SGN:
		return "image_load_pck_sgn";
	case GCN_IMAGE_LOAD_MIP_PCK:
		return "image_load_mip_pck";
	case GCN_IMAGE_LOAD_MIP_PCK_SGN:
		return "image_load_mip_pck_sgn";
	case GCN_IMAGE_STORE:
		return "image_store";
	case GCN_IMAGE_STORE_MIP:
		return "image_store_mip";
	case GCN_IMAGE_STORE_PCK:
		return "image_store_pck";
	case GCN_IMAGE_STORE_MIP_PCK:
		return "image_store_mip_pck";
	case GCN_IMAGE_GET_RESINFO:
		return "image_get_resinfo";
	case GCN_IMAGE_ATOMIC_SWAP:
		return "image_atomic_swap";
	case GCN_IMAGE_ATOMIC_CMPSWAP:
		return "image_atomic_cmpswap";
	case GCN_IMAGE_ATOMIC_ADD:
		return "image_atomic_add";
	case GCN_IMAGE_ATOMIC_SUB:
		return "image_atomic_sub";
	case GCN_IMAGE_ATOMIC_SMIN:
		return "image_atomic_smin";
	case GCN_IMAGE_ATOMIC_UMIN:
		return "image_atomic_umin";
	case GCN_IMAGE_ATOMIC_SMAX:
		return "image_atomic_smax";
	case GCN_IMAGE_ATOMIC_UMAX:
		return "image_atomic_umax";
	case GCN_IMAGE_ATOMIC_AND:
		return "image_atomic_and";
	case GCN_IMAGE_ATOMIC_OR:
		return "image_atomic_or";
	case GCN_IMAGE_ATOMIC_XOR:
		return "image_atomic_xor";
	case GCN_IMAGE_ATOMIC_INC:
		return "image_atomic_inc";
	case GCN_IMAGE_ATOMIC_DEC:
		return "image_atomic_dec";
	case GCN_IMAGE_ATOMIC_FCMPSWAP:
		return "image_atomic_fcmpswap";
	case GCN_IMAGE_ATOMIC_FMIN:
		return "image_atomic_fmin";
	case GCN_IMAGE_ATOMIC_FMAX:
		return "image_atomic_fmax";
	case GCN_IMAGE_SAMPLE:
		return "image_sample";
	case GCN_IMAGE_SAMPLE_CL:
		return "image_sample_cl";
	case GCN_IMAGE_SAMPLE_D:
		return "image_sample_d";
	case GCN_IMAGE_SAMPLE_D_CL:
		return "image_sample_d_cl";
	case GCN_IMAGE_SAMPLE_L:
		return "image_sample_l";
	case GCN_IMAGE_SAMPLE_B:
		return "image_sample_b";
	case GCN_IMAGE_SAMPLE_B_CL:
		return "image_sample_b_cl";
	case GCN_IMAGE_SAMPLE_LZ:
		return "image_sample_lz";
	case GCN_IMAGE_SAMPLE_C:
		return "image_sample_c";
	case GCN_IMAGE_SAMPLE_C_CL:
		return "image_sample_c_cl";
	case GCN_IMAGE_SAMPLE_C_D:
		return "image_sample_c_d";
	case GCN_IMAGE_SAMPLE_C_D_CL:
		return "image_sample_c_d_cl";
	case GCN_IMAGE_SAMPLE_C_L:
		return "image_sample_c_l";
	case GCN_IMAGE_SAMPLE_C_B:
		return "image_sample_c_b";
	case GCN_IMAGE_SAMPLE_C_B_CL:
		return "image_sample_c_b_cl";
	case GCN_IMAGE_SAMPLE_C_LZ:
		return "image_sample_c_lz";
	case GCN_IMAGE_SAMPLE_O:
		return "image_sample_o";
	case GCN_IMAGE_SAMPLE_CL_O:
		return "image_sample_cl_o";
	case GCN_IMAGE_SAMPLE_D_O:
		return "image_sample_d_o";
	case GCN_IMAGE_SAMPLE_D_CL_O:
		return "image_sample_d_cl_o";
	case GCN_IMAGE_SAMPLE_L_O:
		return "image_sample_l_o";
	case GCN_IMAGE_SAMPLE_B_O:
		return "image_sample_b_o";
	case GCN_IMAGE_SAMPLE_B_CL_O:
		return "image_sample_b_cl_o";
	case GCN_IMAGE_SAMPLE_LZ_O:
		return "image_sample_lz_o";
	case GCN_IMAGE_SAMPLE_C_O:
		return "image_sample_c_o";
	case GCN_IMAGE_SAMPLE_C_CL_O:
		return "image_sample_c_cl_o";
	case GCN_IMAGE_SAMPLE_C_D_O:
		return "image_sample_c_d_o";
	case GCN_IMAGE_SAMPLE_C_D_CL_O:
		return "image_sample_c_d_cl_o";
	case GCN_IMAGE_SAMPLE_C_L_O:
		return "image_sample_c_l_o";
	case GCN_IMAGE_SAMPLE_C_B_O:
		return "image_sample_c_b_o";
	case GCN_IMAGE_SAMPLE_C_B_CL_O:
		return "image_sample_c_b_cl_o";
	case GCN_IMAGE_SAMPLE_C_LZ_O:
		return "image_sample_c_lz_o";
	case GCN_IMAGE_GATHER4:
		return "image_gather4";
	case GCN_IMAGE_GATHER4_CL:
		return "image_gather4_cl";
	case GCN_IMAGE_GATHER4_L:
		return "image_gather4_l";
	case GCN_IMAGE_GATHER4_B:
		return "image_gather4_b";
	case GCN_IMAGE_GATHER4_B_CL:
		return "image_gather4_b_cl";
	case GCN_IMAGE_GATHER4_LZ:
		return "image_gather4_lz";
	case GCN_IMAGE_GATHER4_C:
		return "image_gather4_c";
	case GCN_IMAGE_GATHER4_C_CL:
		return "image_gather4_c_cl";
	case GCN_IMAGE_GATHER4_C_L:
		return "image_gather4_c_l";
	case GCN_IMAGE_GATHER4_C_B:
		return "image_gather4_c_b";
	case GCN_IMAGE_GATHER4_C_B_CL:
		return "image_gather4_c_b_cl";
	case GCN_IMAGE_GATHER4_C_LZ:
		return "image_gather4_c_lz";
	case GCN_IMAGE_GATHER4_O:
		return "image_gather4_o";
	case GCN_IMAGE_GATHER4_CL_O:
		return "image_gather4_cl_o";
	case GCN_IMAGE_GATHER4_L_O:
		return "image_gather4_l_o";
	case GCN_IMAGE_GATHER4_B_O:
		return "image_gather4_b_o";
	case GCN_IMAGE_GATHER4_B_CL_O:
		return "image_gather4_b_cl_o";
	case GCN_IMAGE_GATHER4_LZ_O:
		return "image_gather4_lz_o";
	case GCN_IMAGE_GATHER4_C_O:
		return "image_gather4_c_o";
	case GCN_IMAGE_GATHER4_C_CL_O:
		return "image_gather4_c_cl_o";
	case GCN_IMAGE_GATHER4_C_L_O:
		return "image_gather4_c_l_o";
	case GCN_IMAGE_GATHER4_C_B_O:
		return "image_gather4_c_b_o";
	case GCN_IMAGE_GATHER4_C_B_CL_O:
		return "image_gather4_c_b_cl_o";
	case GCN_IMAGE_GATHER4_C_LZ_O:
		return "image_gather4_c_lz_o";
	case GCN_IMAGE_GET_LOD:
		return "image_get_lod";
	case GCN_IMAGE_SAMPLE_CD:
		return "image_sample_cd";
	case GCN_IMAGE_SAMPLE_CD_CL:
		return "image_sample_cd_cl";
	case GCN_IMAGE_SAMPLE_C_CD:
		return "image_sample_c_cd";
	case GCN_IMAGE_SAMPLE_C_CD_CL:
		return "image_sample_c_cd_cl";
	case GCN_IMAGE_SAMPLE_CD_O:
		return "image_sample_cd_o";
	case GCN_IMAGE_SAMPLE_CD_CL_O:
		return "image_sample_cd_cl_o";
	case GCN_IMAGE_SAMPLE_C_CD_O:
		return "image_sample_c_cd_o";
	case GCN_IMAGE_SAMPLE_C_CD_CL_O:
		return "image_sample_c_cd_cl_o";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeMTBUF(GcnOpcodeMTBUF op) {
	switch (op) {
	case GCN_TBUFFER_LOAD_FORMAT_X:
		return "tbuffer_load_format_x";
	case GCN_TBUFFER_LOAD_FORMAT_XY:
		return "tbuffer_load_format_xy";
	case GCN_TBUFFER_LOAD_FORMAT_XYZ:
		return "tbuffer_load_format_xyz";
	case GCN_TBUFFER_LOAD_FORMAT_XYZW:
		return "tbuffer_load_format_xyzw";
	case GCN_TBUFFER_STORE_FORMAT_X:
		return "tbuffer_store_format_x";
	case GCN_TBUFFER_STORE_FORMAT_XY:
		return "tbuffer_store_format_xy";
	case GCN_TBUFFER_STORE_FORMAT_XYZ:
		return "tbuffer_store_format_xyz";
	case GCN_TBUFFER_STORE_FORMAT_XYZW:
		return "tbuffer_store_format_xyzw";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeMUBUF(GcnOpcodeMUBUF op) {
	switch (op) {
	case GCN_BUFFER_LOAD_FORMAT_X:
		return "buffer_load_format_x";
	case GCN_BUFFER_LOAD_FORMAT_XY:
		return "buffer_load_format_xy";
	case GCN_BUFFER_LOAD_FORMAT_XYZ:
		return "buffer_load_format_xyz";
	case GCN_BUFFER_LOAD_FORMAT_XYZW:
		return "buffer_load_format_xyzw";
	case GCN_BUFFER_STORE_FORMAT_X:
		return "buffer_store_format_x";
	case GCN_BUFFER_STORE_FORMAT_XY:
		return "buffer_store_format_xy";
	case GCN_BUFFER_STORE_FORMAT_XYZ:
		return "buffer_store_format_xyz";
	case GCN_BUFFER_STORE_FORMAT_XYZW:
		return "buffer_store_format_xyzw";
	case GCN_BUFFER_LOAD_UBYTE:
		return "buffer_load_ubyte";
	case GCN_BUFFER_LOAD_SBYTE:
		return "buffer_load_sbyte";
	case GCN_BUFFER_LOAD_USHORT:
		return "buffer_load_ushort";
	case GCN_BUFFER_LOAD_SSHORT:
		return "buffer_load_sshort";
	case GCN_BUFFER_LOAD_DWORD:
		return "buffer_load_dword";
	case GCN_BUFFER_LOAD_DWORDX2:
		return "buffer_load_dwordx2";
	case GCN_BUFFER_LOAD_DWORDX4:
		return "buffer_load_dwordx4";
	case GCN_BUFFER_LOAD_DWORDX3:
		return "buffer_load_dwordx3";
	case GCN_BUFFER_STORE_BYTE:
		return "buffer_store_byte";
	case GCN_BUFFER_STORE_SHORT:
		return "buffer_store_short";
	case GCN_BUFFER_STORE_DWORD:
		return "buffer_store_dword";
	case GCN_BUFFER_STORE_DWORDX2:
		return "buffer_store_dwordx2";
	case GCN_BUFFER_STORE_DWORDX4:
		return "buffer_store_dwordx4";
	case GCN_BUFFER_STORE_DWORDX3:
		return "buffer_store_dwordx3";
	case GCN_BUFFER_ATOMIC_SWAP:
		return "buffer_atomic_swap";
	case GCN_BUFFER_ATOMIC_CMPSWAP:
		return "buffer_atomic_cmpswap";
	case GCN_BUFFER_ATOMIC_ADD:
		return "buffer_atomic_add";
	case GCN_BUFFER_ATOMIC_SUB:
		return "buffer_atomic_sub";
	case GCN_BUFFER_ATOMIC_SMIN:
		return "buffer_atomic_smin";
	case GCN_BUFFER_ATOMIC_UMIN:
		return "buffer_atomic_umin";
	case GCN_BUFFER_ATOMIC_SMAX:
		return "buffer_atomic_smax";
	case GCN_BUFFER_ATOMIC_UMAX:
		return "buffer_atomic_umax";
	case GCN_BUFFER_ATOMIC_AND:
		return "buffer_atomic_and";
	case GCN_BUFFER_ATOMIC_OR:
		return "buffer_atomic_or";
	case GCN_BUFFER_ATOMIC_XOR:
		return "buffer_atomic_xor";
	case GCN_BUFFER_ATOMIC_INC:
		return "buffer_atomic_inc";
	case GCN_BUFFER_ATOMIC_DEC:
		return "buffer_atomic_dec";
	case GCN_BUFFER_ATOMIC_FCMPSWAP:
		return "buffer_atomic_fcmpswap";
	case GCN_BUFFER_ATOMIC_FMIN:
		return "buffer_atomic_fmin";
	case GCN_BUFFER_ATOMIC_FMAX:
		return "buffer_atomic_fmax";
	case GCN_BUFFER_ATOMIC_SWAP_X2:
		return "buffer_atomic_swap_x2";
	case GCN_BUFFER_ATOMIC_CMPSWAP_X2:
		return "buffer_atomic_cmpswap_x2";
	case GCN_BUFFER_ATOMIC_ADD_X2:
		return "buffer_atomic_add_x2";
	case GCN_BUFFER_ATOMIC_SUB_X2:
		return "buffer_atomic_sub_x2";
	case GCN_BUFFER_ATOMIC_SMIN_X2:
		return "buffer_atomic_smin_x2";
	case GCN_BUFFER_ATOMIC_UMIN_X2:
		return "buffer_atomic_umin_x2";
	case GCN_BUFFER_ATOMIC_SMAX_X2:
		return "buffer_atomic_smax_x2";
	case GCN_BUFFER_ATOMIC_UMAX_X2:
		return "buffer_atomic_umax_x2";
	case GCN_BUFFER_ATOMIC_AND_X2:
		return "buffer_atomic_and_x2";
	case GCN_BUFFER_ATOMIC_OR_X2:
		return "buffer_atomic_or_x2";
	case GCN_BUFFER_ATOMIC_XOR_X2:
		return "buffer_atomic_xor_x2";
	case GCN_BUFFER_ATOMIC_INC_X2:
		return "buffer_atomic_inc_x2";
	case GCN_BUFFER_ATOMIC_DEC_X2:
		return "buffer_atomic_dec_x2";
	case GCN_BUFFER_ATOMIC_FCMPSWAP_X2:
		return "buffer_atomic_fcmpswap_x2";
	case GCN_BUFFER_ATOMIC_FMIN_X2:
		return "buffer_atomic_fmin_x2";
	case GCN_BUFFER_ATOMIC_FMAX_X2:
		return "buffer_atomic_fmax_x2";
	case GCN_BUFFER_WBINVL1_SC:
		return "buffer_wbinvl1_sc";
	case GCN_BUFFER_WBINVL1:
		return "buffer_wbinvl1";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSMRD(GcnOpcodeSMRD op) {
	switch (op) {
	case GCN_S_LOAD_DWORD:
		return "s_load_dword";
	case GCN_S_LOAD_DWORDX2:
		return "s_load_dwordx2";
	case GCN_S_LOAD_DWORDX4:
		return "s_load_dwordx4";
	case GCN_S_LOAD_DWORDX8:
		return "s_load_dwordx8";
	case GCN_S_LOAD_DWORDX16:
		return "s_load_dwordx16";
	case GCN_S_BUFFER_LOAD_DWORD:
		return "s_buffer_load_dword";
	case GCN_S_BUFFER_LOAD_DWORDX2:
		return "s_buffer_load_dwordx2";
	case GCN_S_BUFFER_LOAD_DWORDX4:
		return "s_buffer_load_dwordx4";
	case GCN_S_BUFFER_LOAD_DWORDX8:
		return "s_buffer_load_dwordx8";
	case GCN_S_BUFFER_LOAD_DWORDX16:
		return "s_buffer_load_dwordx16";
	case GCN_S_DCACHE_INV_VOL:
		return "s_dcache_inv_vol";
	case GCN_S_MEMTIME:
		return "s_memtime";
	case GCN_S_DCACHE_INV:
		return "s_dcache_inv";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSOP1(GcnOpcodeSOP1 op) {
	switch (op) {
	case GCN_S_MOV_B32:
		return "s_mov_b32";
	case GCN_S_MOV_B64:
		return "s_mov_b64";
	case GCN_S_CMOV_B32:
		return "s_cmov_b32";
	case GCN_S_CMOV_B64:
		return "s_cmov_b64";
	case GCN_S_NOT_B32:
		return "s_not_b32";
	case GCN_S_NOT_B64:
		return "s_not_b64";
	case GCN_S_WQM_B32:
		return "s_wqm_b32";
	case GCN_S_WQM_B64:
		return "s_wqm_b64";
	case GCN_S_BREV_B32:
		return "s_brev_b32";
	case GCN_S_BREV_B64:
		return "s_brev_b64";
	case GCN_S_BCNT0_I32_B32:
		return "s_bcnt0_i32_b32";
	case GCN_S_BCNT0_I32_B64:
		return "s_bcnt0_i32_b64";
	case GCN_S_BCNT1_I32_B32:
		return "s_bcnt1_i32_b32";
	case GCN_S_BCNT1_I32_B64:
		return "s_bcnt1_i32_b64";
	case GCN_S_FF0_I32_B32:
		return "s_ff0_i32_b32";
	case GCN_S_FF0_I32_B64:
		return "s_ff0_i32_b64";
	case GCN_S_FF1_I32_B32:
		return "s_ff1_i32_b32";
	case GCN_S_FF1_I32_B64:
		return "s_ff1_i32_b64";
	case GCN_S_FLBIT_I32_B32:
		return "s_flbit_i32_b32";
	case GCN_S_FLBIT_I32_B64:
		return "s_flbit_i32_b64";
	case GCN_S_FLBIT_I32:
		return "s_flbit_i32";
	case GCN_S_FLBIT_I32_I64:
		return "s_flbit_i32_i64";
	case GCN_S_SEXT_I32_I8:
		return "s_sext_i32_i8";
	case GCN_S_SEXT_I32_I16:
		return "s_sext_i32_i16";
	case GCN_S_BITSET0_B32:
		return "s_bitset0_b32";
	case GCN_S_BITSET0_B64:
		return "s_bitset0_b64";
	case GCN_S_BITSET1_B32:
		return "s_bitset1_b32";
	case GCN_S_BITSET1_B64:
		return "s_bitset1_b64";
	case GCN_S_GETPC_B64:
		return "s_getpc_b64";
	case GCN_S_SETPC_B64:
		return "s_setpc_b64";
	case GCN_S_SWAPPC_B64:
		return "s_swappc_b64";
	case GCN_S_RFE_B64:
		return "s_rfe_b64";
	case GCN_S_AND_SAVEEXEC_B64:
		return "s_and_saveexec_b64";
	case GCN_S_OR_SAVEEXEC_B64:
		return "s_or_saveexec_b64";
	case GCN_S_XOR_SAVEEXEC_B64:
		return "s_xor_saveexec_b64";
	case GCN_S_ANDN2_SAVEEXEC_B64:
		return "s_andn2_saveexec_b64";
	case GCN_S_ORN2_SAVEEXEC_B64:
		return "s_orn2_saveexec_b64";
	case GCN_S_NAND_SAVEEXEC_B64:
		return "s_nand_saveexec_b64";
	case GCN_S_NOR_SAVEEXEC_B64:
		return "s_nor_saveexec_b64";
	case GCN_S_XNOR_SAVEEXEC_B64:
		return "s_xnor_saveexec_b64";
	case GCN_S_QUADMASK_B32:
		return "s_quadmask_b32";
	case GCN_S_QUADMASK_B64:
		return "s_quadmask_b64";
	case GCN_S_MOVRELS_B32:
		return "s_movrels_b32";
	case GCN_S_MOVRELS_B64:
		return "s_movrels_b64";
	case GCN_S_MOVRELD_B32:
		return "s_movreld_b32";
	case GCN_S_MOVRELD_B64:
		return "s_movreld_b64";
	case GCN_S_CBRANCH_JOIN:
		return "s_cbranch_join";
	case GCN_S_MOV_REGRD_B32:
		return "s_mov_regrd_b32";
	case GCN_S_ABS_I32:
		return "s_abs_i32";
	case GCN_S_MOV_FED_B32:
		return "s_mov_fed_b32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSOP2(GcnOpcodeSOP2 op) {
	switch (op) {
	case GCN_S_ADD_U32:
		return "s_add_u32";
	case GCN_S_SUB_U32:
		return "s_sub_u32";
	case GCN_S_ADD_I32:
		return "s_add_i32";
	case GCN_S_SUB_I32:
		return "s_sub_i32";
	case GCN_S_ADDC_U32:
		return "s_addc_u32";
	case GCN_S_SUBB_U32:
		return "s_subb_u32";
	case GCN_S_MIN_I32:
		return "s_min_i32";
	case GCN_S_MIN_U32:
		return "s_min_u32";
	case GCN_S_MAX_I32:
		return "s_max_i32";
	case GCN_S_MAX_U32:
		return "s_max_u32";
	case GCN_S_CSELECT_B32:
		return "s_cselect_b32";
	case GCN_S_CSELECT_B64:
		return "s_cselect_b64";
	case GCN_S_AND_B32:
		return "s_and_b32";
	case GCN_S_AND_B64:
		return "s_and_b64";
	case GCN_S_OR_B32:
		return "s_or_b32";
	case GCN_S_OR_B64:
		return "s_or_b64";
	case GCN_S_XOR_B32:
		return "s_xor_b32";
	case GCN_S_XOR_B64:
		return "s_xor_b64";
	case GCN_S_ANDN2_B32:
		return "s_andn2_b32";
	case GCN_S_ANDN2_B64:
		return "s_andn2_b64";
	case GCN_S_ORN2_B32:
		return "s_orn2_b32";
	case GCN_S_ORN2_B64:
		return "s_orn2_b64";
	case GCN_S_NAND_B32:
		return "s_nand_b32";
	case GCN_S_NAND_B64:
		return "s_nand_b64";
	case GCN_S_NOR_B32:
		return "s_nor_b32";
	case GCN_S_NOR_B64:
		return "s_nor_b64";
	case GCN_S_XNOR_B32:
		return "s_xnor_b32";
	case GCN_S_XNOR_B64:
		return "s_xnor_b64";
	case GCN_S_LSHL_B32:
		return "s_lshl_b32";
	case GCN_S_LSHL_B64:
		return "s_lshl_b64";
	case GCN_S_LSHR_B32:
		return "s_lshr_b32";
	case GCN_S_LSHR_B64:
		return "s_lshr_b64";
	case GCN_S_ASHR_I32:
		return "s_ashr_i32";
	case GCN_S_ASHR_I64:
		return "s_ashr_i64";
	case GCN_S_BFM_B32:
		return "s_bfm_b32";
	case GCN_S_BFM_B64:
		return "s_bfm_b64";
	case GCN_S_MUL_I32:
		return "s_mul_i32";
	case GCN_S_BFE_U32:
		return "s_bfe_u32";
	case GCN_S_BFE_I32:
		return "s_bfe_i32";
	case GCN_S_BFE_U64:
		return "s_bfe_u64";
	case GCN_S_BFE_I64:
		return "s_bfe_i64";
	case GCN_S_CBRANCH_G_FORK:
		return "s_cbranch_g_fork";
	case GCN_S_ABSDIFF_I32:
		return "s_absdiff_i32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSOPC(GcnOpcodeSOPC op) {
	switch (op) {
	case GCN_S_CMP_EQ_I32:
		return "s_cmp_eq_i32";
	case GCN_S_CMP_LG_I32:
		return "s_cmp_lg_i32";
	case GCN_S_CMP_GT_I32:
		return "s_cmp_gt_i32";
	case GCN_S_CMP_GE_I32:
		return "s_cmp_ge_i32";
	case GCN_S_CMP_LT_I32:
		return "s_cmp_lt_i32";
	case GCN_S_CMP_LE_I32:
		return "s_cmp_le_i32";
	case GCN_S_CMP_EQ_U32:
		return "s_cmp_eq_u32";
	case GCN_S_CMP_LG_U32:
		return "s_cmp_lg_u32";
	case GCN_S_CMP_GT_U32:
		return "s_cmp_gt_u32";
	case GCN_S_CMP_GE_U32:
		return "s_cmp_ge_u32";
	case GCN_S_CMP_LT_U32:
		return "s_cmp_lt_u32";
	case GCN_S_CMP_LE_U32:
		return "s_cmp_le_u32";
	case GCN_S_BITCMP0_B32:
		return "s_bitcmp0_b32";
	case GCN_S_BITCMP1_B32:
		return "s_bitcmp1_b32";
	case GCN_S_BITCMP0_B64:
		return "s_bitcmp0_b64";
	case GCN_S_BITCMP1_B64:
		return "s_bitcmp1_b64";
	case GCN_S_SETVSKIP:
		return "s_setvskip";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSOPK(GcnOpcodeSOPK op) {
	switch (op) {
	case GCN_S_MOVK_I32:
		return "s_movk_i32";
	case GCN_S_CMOVK_I32:
		return "s_cmovk_i32";
	case GCN_S_CMPK_EQ_I32:
		return "s_cmpk_eq_i32";
	case GCN_S_CMPK_LG_I32:
		return "s_cmpk_lg_i32";
	case GCN_S_CMPK_GT_I32:
		return "s_cmpk_gt_i32";
	case GCN_S_CMPK_GE_I32:
		return "s_cmpk_ge_i32";
	case GCN_S_CMPK_LT_I32:
		return "s_cmpk_lt_i32";
	case GCN_S_CMPK_LE_I32:
		return "s_cmpk_le_i32";
	case GCN_S_CMPK_EQ_U32:
		return "s_cmpk_eq_u32";
	case GCN_S_CMPK_LG_U32:
		return "s_cmpk_lg_u32";
	case GCN_S_CMPK_GT_U32:
		return "s_cmpk_gt_u32";
	case GCN_S_CMPK_GE_U32:
		return "s_cmpk_ge_u32";
	case GCN_S_CMPK_LT_U32:
		return "s_cmpk_lt_u32";
	case GCN_S_CMPK_LE_U32:
		return "s_cmpk_le_u32";
	case GCN_S_ADDK_I32:
		return "s_addk_i32";
	case GCN_S_MULK_I32:
		return "s_mulk_i32";
	case GCN_S_CBRANCH_I_FORK:
		return "s_cbranch_i_fork";
	case GCN_S_GETREG_B32:
		return "s_getreg_b32";
	case GCN_S_SETREG_B32:
		return "s_setreg_b32";
	case GCN_S_GETREG_REGRD_B32:
		return "s_getreg_b32_regrd_b32";
	case GCN_S_SETREG_IMM32_B32:
		return "s_setreg_b32_imm32_b32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeSOPP(GcnOpcodeSOPP op) {
	switch (op) {
	case GCN_S_NOP:
		return "s_nop";
	case GCN_S_ENDPGM:
		return "s_endpgm";
	case GCN_S_BRANCH:
		return "s_branch";
	case GCN_S_CBRANCH_SCC0:
		return "s_cbranch_scc0";
	case GCN_S_CBRANCH_SCC1:
		return "s_cbranch_scc1";
	case GCN_S_CBRANCH_VCCZ:
		return "s_cbranch_vccz";
	case GCN_S_CBRANCH_VCCNZ:
		return "s_cbranch_vccnz";
	case GCN_S_CBRANCH_EXECZ:
		return "s_cbranch_execz";
	case GCN_S_CBRANCH_EXECNZ:
		return "s_cbranch_execnz";
	case GCN_S_BARRIER:
		return "s_barrier";
	case GCN_S_SETKILL:
		return "s_setkill";
	case GCN_S_WAITCNT:
		return "s_waitcnt";
	case GCN_S_SETHALT:
		return "s_sethalt";
	case GCN_S_SLEEP:
		return "s_sleep";
	case GCN_S_SETPRIO:
		return "s_setprio";
	case GCN_S_SENDMSG:
		return "s_sendmsg";
	case GCN_S_SENDMSGHALT:
		return "s_sendmsghalt";
	case GCN_S_TRAP:
		return "s_trap";
	case GCN_S_ICACHE_INV:
		return "s_icache_inv";
	case GCN_S_INCPERFLEVEL:
		return "s_incperflevel";
	case GCN_S_DECPERFLEVEL:
		return "s_decperflevel";
	case GCN_S_TTRACEDATA:
		return "s_ttracedata";
	case GCN_S_CBRANCH_CDBGSYS:
		return "s_cbranch_cdbgsys";
	case GCN_S_CBRANCH_CDBGUSER:
		return "s_cbranch_cdbguser";
	case GCN_S_CBRANCH_CDBGSYS_OR_USER:
		return "s_cbranch_cdbgsys_or_user";
	case GCN_S_CBRANCH_CDBGSYS_AND_USER:
		return "s_cbranch_cdbgsys_and_user";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeVINTRP(GcnOpcodeVINTRP op) {
	switch (op) {
	case GCN_V_INTERP_P1_F32:
		return "v_interp_p1_f32";
	case GCN_V_INTERP_P2_F32:
		return "v_interp_p2_f32";
	case GCN_V_INTERP_MOV_F32:
		return "v_interp_mov_f32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeVOP1(GcnOpcodeVOP1 op) {
	switch (op) {
	case GCN_V_NOP:
		return "v_nop";
	case GCN_V_MOV_B32:
		return "v_mov_b32";
	case GCN_V_READFIRSTLANE_B32:
		return "v_readfirstlane_b32";
	case GCN_V_CVT_I32_F64:
		return "v_cvt_i32_f64";
	case GCN_V_CVT_F64_I32:
		return "v_cvt_f64_i32";
	case GCN_V_CVT_F32_I32:
		return "v_cvt_f32_i32";
	case GCN_V_CVT_F32_U32:
		return "v_cvt_f32_u32";
	case GCN_V_CVT_U32_F32:
		return "v_cvt_u32_f32";
	case GCN_V_CVT_I32_F32:
		return "v_cvt_i32_f32";
	case GCN_V_MOV_FED_B32:
		return "v_mov_fed_b32";
	case GCN_V_CVT_F16_F32:
		return "v_cvt_f16_f32";
	case GCN_V_CVT_F32_F16:
		return "v_cvt_f32_f16";
	case GCN_V_CVT_RPI_I32_F32:
		return "v_cvt_rpi_i32_f32";
	case GCN_V_CVT_FLR_I32_F32:
		return "v_cvt_flr_i32_f32";
	case GCN_V_CVT_OFF_F32_I4:
		return "v_cvt_off_f32_i4";
	case GCN_V_CVT_F32_F64:
		return "v_cvt_f32_f64";
	case GCN_V_CVT_F64_F32:
		return "v_cvt_f64_f32";
	case GCN_V_CVT_F32_UBYTE0:
		return "v_cvt_f32_ubyte0";
	case GCN_V_CVT_F32_UBYTE1:
		return "v_cvt_f32_ubyte1";
	case GCN_V_CVT_F32_UBYTE2:
		return "v_cvt_f32_ubyte2";
	case GCN_V_CVT_F32_UBYTE3:
		return "v_cvt_f32_ubyte3";
	case GCN_V_CVT_U32_F64:
		return "v_cvt_u32_f64";
	case GCN_V_CVT_F64_U32:
		return "v_cvt_f64_u32";
	case GCN_V_TRUNC_F64:
		return "v_trunc_f64";
	case GCN_V_CEIL_F64:
		return "v_ceil_f64";
	case GCN_V_RNDNE_F64:
		return "v_rndne_f64";
	case GCN_V_FLOOR_F64:
		return "v_floor_f64";
	case GCN_V_FRACT_F32:
		return "v_fract_f32";
	case GCN_V_TRUNC_F32:
		return "v_trunc_f32";
	case GCN_V_CEIL_F32:
		return "v_ceil_f32";
	case GCN_V_RNDNE_F32:
		return "v_rndne_f32";
	case GCN_V_FLOOR_F32:
		return "v_floor_f32";
	case GCN_V_EXP_F32:
		return "v_exp_f32";
	case GCN_V_LOG_CLAMP_F32:
		return "v_log_clamp_f32";
	case GCN_V_LOG_F32:
		return "v_log_f32";
	case GCN_V_RCP_CLAMP_F32:
		return "v_rcp_clamp_f32";
	case GCN_V_RCP_LEGACY_F32:
		return "v_rcp_legacy_f32";
	case GCN_V_RCP_F32:
		return "v_rcp_f32";
	case GCN_V_RCP_IFLAG_F32:
		return "v_rcp_iflag_f32";
	case GCN_V_RSQ_CLAMP_F32:
		return "v_rsq_clamp_f32";
	case GCN_V_RSQ_LEGACY_F32:
		return "v_rsq_legacy_f32";
	case GCN_V_RSQ_F32:
		return "v_rsq_f32";
	case GCN_V_RCP_F64:
		return "v_rcp_f64";
	case GCN_V_RCP_CLAMP_F64:
		return "v_rcp_clamp_f64";
	case GCN_V_RSQ_F64:
		return "v_rsq_f64";
	case GCN_V_RSQ_CLAMP_F64:
		return "v_rsq_clamp_f64";
	case GCN_V_SQRT_F32:
		return "v_sqrt_f32";
	case GCN_V_SQRT_F64:
		return "v_sqrt_f64";
	case GCN_V_SIN_F32:
		return "v_sin_f32";
	case GCN_V_COS_F32:
		return "v_cos_f32";
	case GCN_V_NOT_B32:
		return "v_not_b32";
	case GCN_V_BFREV_B32:
		return "v_bfrev_b32";
	case GCN_V_FFBH_U32:
		return "v_ffbh_u32";
	case GCN_V_FFBL_B32:
		return "v_ffbl_b32";
	case GCN_V_FFBH_I32:
		return "v_ffbh_i32";
	case GCN_V_FREXP_EXP_I32_F64:
		return "v_frexp_exp_i32_f64";
	case GCN_V_FREXP_MANT_F64:
		return "v_frexp_mant_f64";
	case GCN_V_FRACT_F64:
		return "v_fract_f64";
	case GCN_V_FREXP_EXP_I32_F32:
		return "v_frexp_exp_i32_f32";
	case GCN_V_FREXP_MANT_F32:
		return "v_frexp_mant_f32";
	case GCN_V_CLREXCP:
		return "v_clrexcp";
	case GCN_V_MOVRELD_B32:
		return "v_movreld_b32";
	case GCN_V_MOVRELS_B32:
		return "v_movrels_b32";
	case GCN_V_MOVRELSD_B32:
		return "v_movrelsd_b32";
	case GCN_V_LOG_LEGACY_F32:
		return "v_log_legacy_f32";
	case GCN_V_EXP_LEGACY_F32:
		return "v_exp_legacy_f32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeVOP2(GcnOpcodeVOP2 op) {
	switch (op) {
	case GCN_V_CNDMASK_B32:
		return "v_cndmask_b32";
	case GCN_V_READLANE_B32:
		return "v_readlane_b32";
	case GCN_V_WRITELANE_B32:
		return "v_writelane_b32";
	case GCN_V_ADD_F32:
		return "v_add_f32";
	case GCN_V_SUB_F32:
		return "v_sub_f32";
	case GCN_V_SUBREV_F32:
		return "v_subrev_f32";
	case GCN_V_MAC_LEGACY_F32:
		return "v_mac_legacy_f32";
	case GCN_V_MUL_LEGACY_F32:
		return "v_mul_legacy_f32";
	case GCN_V_MUL_F32:
		return "v_mul_f32";
	case GCN_V_MUL_I32_I24:
		return "v_mul_i32_i24";
	case GCN_V_MUL_HI_I32_I24:
		return "v_mul_hi_i32_i24";
	case GCN_V_MUL_U32_U24:
		return "v_mul_u32_u24";
	case GCN_V_MUL_HI_U32_U24:
		return "v_mul_hi_u32_u24";
	case GCN_V_MIN_LEGACY_F32:
		return "v_min_legacy_f32";
	case GCN_V_MAX_LEGACY_F32:
		return "v_max_legacy_f32";
	case GCN_V_MIN_F32:
		return "v_min_f32";
	case GCN_V_MAX_F32:
		return "v_max_f32";
	case GCN_V_MIN_I32:
		return "v_min_i32";
	case GCN_V_MAX_I32:
		return "v_max_i32";
	case GCN_V_MIN_U32:
		return "v_min_u32";
	case GCN_V_MAX_U32:
		return "v_max_u32";
	case GCN_V_LSHR_B32:
		return "v_lshr_b32";
	case GCN_V_LSHRREV_B32:
		return "v_lshrrev_b32";
	case GCN_V_ASHR_I32:
		return "v_ashr_i32";
	case GCN_V_ASHRREV_I32:
		return "v_ashrrev_i32";
	case GCN_V_LSHL_B32:
		return "v_lshl_b32";
	case GCN_V_LSHLREV_B32:
		return "v_lshlrev_b32";
	case GCN_V_AND_B32:
		return "v_and_b32";
	case GCN_V_OR_B32:
		return "v_or_b32";
	case GCN_V_XOR_B32:
		return "v_xor_b32";
	case GCN_V_BFM_B32:
		return "v_bfm_b32";
	case GCN_V_MAC_F32:
		return "v_mac_f32";
	case GCN_V_MADMK_F32:
		return "v_madmk_f32";
	case GCN_V_MADAK_F32:
		return "v_madak_f32";
	case GCN_V_BCNT_U32_B32:
		return "v_bcnt_u32_b32";
	case GCN_V_MBCNT_LO_U32_B32:
		return "v_mbcnt_lo_u32_b32";
	case GCN_V_MBCNT_HI_U32_B32:
		return "v_mbcnt_hi_u32_b32";
	case GCN_V_ADD_I32:
		return "v_add_i32";
	case GCN_V_SUB_I32:
		return "v_sub_i32";
	case GCN_V_SUBREV_I32:
		return "v_subrev_i32";
	case GCN_V_ADDC_U32:
		return "v_addc_u32";
	case GCN_V_SUBB_U32:
		return "v_subb_u32";
	case GCN_V_SUBBREV_U32:
		return "v_subbrev_u32";
	case GCN_V_LDEXP_F32:
		return "v_ldexp_f32";
	case GCN_V_CVT_PKACCUM_U8_F32:
		return "v_cvt_pkaccum_u8_f32";
	case GCN_V_CVT_PKNORM_I16_F32:
		return "v_cvt_pknorm_i16_f32";
	case GCN_V_CVT_PKNORM_U16_F32:
		return "v_cvt_pknorm_u16_f32";
	case GCN_V_CVT_PKRTZ_F16_F32:
		return "v_cvt_pkrtz_f16_f32";
	case GCN_V_CVT_PK_U16_U32:
		return "v_cvt_pk_u16_u32";
	case GCN_V_CVT_PK_I16_I32:
		return "v_cvt_pk_i16_i32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeVOP3(GcnOpcodeVOP3 op) {
	switch (op) {
	case GCN_V_CMP_F_F32_E64:
		return "v_cmp_f_f32";
	case GCN_V_CMP_LT_F32_E64:
		return "v_cmp_lt_f32";
	case GCN_V_CMP_EQ_F32_E64:
		return "v_cmp_eq_f32";
	case GCN_V_CMP_LE_F32_E64:
		return "v_cmp_le_f32";
	case GCN_V_CMP_GT_F32_E64:
		return "v_cmp_gt_f32";
	case GCN_V_CMP_LG_F32_E64:
		return "v_cmp_lg_f32";
	case GCN_V_CMP_GE_F32_E64:
		return "v_cmp_ge_f32";
	case GCN_V_CMP_O_F32_E64:
		return "v_cmp_o_f32";
	case GCN_V_CMP_U_F32_E64:
		return "v_cmp_u_f32";
	case GCN_V_CMP_NGE_F32_E64:
		return "v_cmp_nge_f32";
	case GCN_V_CMP_NLG_F32_E64:
		return "v_cmp_nlg_f32";
	case GCN_V_CMP_NGT_F32_E64:
		return "v_cmp_ngt_f32";
	case GCN_V_CMP_NLE_F32_E64:
		return "v_cmp_nle_f32";
	case GCN_V_CMP_NEQ_F32_E64:
		return "v_cmp_neq_f32";
	case GCN_V_CMP_NLT_F32_E64:
		return "v_cmp_nlt_f32";
	case GCN_V_CMP_TRU_F32_E64:
		return "v_cmp_tru_f32";
	case GCN_V_CMPX_F_F32_E64:
		return "v_cmpx_f_f32";
	case GCN_V_CMPX_LT_F32_E64:
		return "v_cmpx_lt_f32";
	case GCN_V_CMPX_EQ_F32_E64:
		return "v_cmpx_eq_f32";
	case GCN_V_CMPX_LE_F32_E64:
		return "v_cmpx_le_f32";
	case GCN_V_CMPX_GT_F32_E64:
		return "v_cmpx_gt_f32";
	case GCN_V_CMPX_LG_F32_E64:
		return "v_cmpx_lg_f32";
	case GCN_V_CMPX_GE_F32_E64:
		return "v_cmpx_ge_f32";
	case GCN_V_CMPX_O_F32_E64:
		return "v_cmpx_o_f32";
	case GCN_V_CMPX_U_F32_E64:
		return "v_cmpx_u_f32";
	case GCN_V_CMPX_NGE_F32_E64:
		return "v_cmpx_nge_f32";
	case GCN_V_CMPX_NLG_F32_E64:
		return "v_cmpx_nlg_f32";
	case GCN_V_CMPX_NGT_F32_E64:
		return "v_cmpx_ngt_f32";
	case GCN_V_CMPX_NLE_F32_E64:
		return "v_cmpx_nle_f32";
	case GCN_V_CMPX_NEQ_F32_E64:
		return "v_cmpx_neq_f32";
	case GCN_V_CMPX_NLT_F32_E64:
		return "v_cmpx_nlt_f32";
	case GCN_V_CMPX_TRU_F32_E64:
		return "v_cmpx_tru_f32";
	case GCN_V_CMP_F_F64_E64:
		return "v_cmp_f_f64";
	case GCN_V_CMP_LT_F64_E64:
		return "v_cmp_lt_f64";
	case GCN_V_CMP_EQ_F64_E64:
		return "v_cmp_eq_f64";
	case GCN_V_CMP_LE_F64_E64:
		return "v_cmp_le_f64";
	case GCN_V_CMP_GT_F64_E64:
		return "v_cmp_gt_f64";
	case GCN_V_CMP_LG_F64_E64:
		return "v_cmp_lg_f64";
	case GCN_V_CMP_GE_F64_E64:
		return "v_cmp_ge_f64";
	case GCN_V_CMP_O_F64_E64:
		return "v_cmp_o_f64";
	case GCN_V_CMP_U_F64_E64:
		return "v_cmp_u_f64";
	case GCN_V_CMP_NGE_F64_E64:
		return "v_cmp_nge_f64";
	case GCN_V_CMP_NLG_F64_E64:
		return "v_cmp_nlg_f64";
	case GCN_V_CMP_NGT_F64_E64:
		return "v_cmp_ngt_f64";
	case GCN_V_CMP_NLE_F64_E64:
		return "v_cmp_nle_f64";
	case GCN_V_CMP_NEQ_F64_E64:
		return "v_cmp_neq_f64";
	case GCN_V_CMP_NLT_F64_E64:
		return "v_cmp_nlt_f64";
	case GCN_V_CMP_TRU_F64_E64:
		return "v_cmp_tru_f64";
	case GCN_V_CMPX_F_F64_E64:
		return "v_cmpx_f_f64";
	case GCN_V_CMPX_LT_F64_E64:
		return "v_cmpx_lt_f64";
	case GCN_V_CMPX_EQ_F64_E64:
		return "v_cmpx_eq_f64";
	case GCN_V_CMPX_LE_F64_E64:
		return "v_cmpx_le_f64";
	case GCN_V_CMPX_GT_F64_E64:
		return "v_cmpx_gt_f64";
	case GCN_V_CMPX_LG_F64_E64:
		return "v_cmpx_lg_f64";
	case GCN_V_CMPX_GE_F64_E64:
		return "v_cmpx_ge_f64";
	case GCN_V_CMPX_O_F64_E64:
		return "v_cmpx_o_f64";
	case GCN_V_CMPX_U_F64_E64:
		return "v_cmpx_u_f64";
	case GCN_V_CMPX_NGE_F64_E64:
		return "v_cmpx_nge_f64";
	case GCN_V_CMPX_NLG_F64_E64:
		return "v_cmpx_nlg_f64";
	case GCN_V_CMPX_NGT_F64_E64:
		return "v_cmpx_ngt_f64";
	case GCN_V_CMPX_NLE_F64_E64:
		return "v_cmpx_nle_f64";
	case GCN_V_CMPX_NEQ_F64_E64:
		return "v_cmpx_neq_f64";
	case GCN_V_CMPX_NLT_F64_E64:
		return "v_cmpx_nlt_f64";
	case GCN_V_CMPX_TRU_F64_E64:
		return "v_cmpx_tru_f64";
	case GCN_V_CMPS_F_F32_E64:
		return "v_cmps_f_f32";
	case GCN_V_CMPS_LT_F32_E64:
		return "v_cmps_lt_f32";
	case GCN_V_CMPS_EQ_F32_E64:
		return "v_cmps_eq_f32";
	case GCN_V_CMPS_LE_F32_E64:
		return "v_cmps_le_f32";
	case GCN_V_CMPS_GT_F32_E64:
		return "v_cmps_gt_f32";
	case GCN_V_CMPS_LG_F32_E64:
		return "v_cmps_lg_f32";
	case GCN_V_CMPS_GE_F32_E64:
		return "v_cmps_ge_f32";
	case GCN_V_CMPS_O_F32_E64:
		return "v_cmps_o_f32";
	case GCN_V_CMPS_U_F32_E64:
		return "v_cmps_u_f32";
	case GCN_V_CMPS_NGE_F32_E64:
		return "v_cmps_nge_f32";
	case GCN_V_CMPS_NLG_F32_E64:
		return "v_cmps_nlg_f32";
	case GCN_V_CMPS_NGT_F32_E64:
		return "v_cmps_ngt_f32";
	case GCN_V_CMPS_NLE_F32_E64:
		return "v_cmps_nle_f32";
	case GCN_V_CMPS_NEQ_F32_E64:
		return "v_cmps_neq_f32";
	case GCN_V_CMPS_NLT_F32_E64:
		return "v_cmps_nlt_f32";
	case GCN_V_CMPS_TRU_F32_E64:
		return "v_cmps_tru_f32";
	case GCN_V_CMPSX_F_F32_E64:
		return "v_cmpsx_f_f32";
	case GCN_V_CMPSX_LT_F32_E64:
		return "v_cmpsx_lt_f32";
	case GCN_V_CMPSX_EQ_F32_E64:
		return "v_cmpsx_eq_f32";
	case GCN_V_CMPSX_LE_F32_E64:
		return "v_cmpsx_le_f32";
	case GCN_V_CMPSX_GT_F32_E64:
		return "v_cmpsx_gt_f32";
	case GCN_V_CMPSX_LG_F32_E64:
		return "v_cmpsx_lg_f32";
	case GCN_V_CMPSX_GE_F32_E64:
		return "v_cmpsx_ge_f32";
	case GCN_V_CMPSX_O_F32_E64:
		return "v_cmpsx_o_f32";
	case GCN_V_CMPSX_U_F32_E64:
		return "v_cmpsx_u_f32";
	case GCN_V_CMPSX_NGE_F32_E64:
		return "v_cmpsx_nge_f32";
	case GCN_V_CMPSX_NLG_F32_E64:
		return "v_cmpsx_nlg_f32";
	case GCN_V_CMPSX_NGT_F32_E64:
		return "v_cmpsx_ngt_f32";
	case GCN_V_CMPSX_NLE_F32_E64:
		return "v_cmpsx_nle_f32";
	case GCN_V_CMPSX_NEQ_F32_E64:
		return "v_cmpsx_neq_f32";
	case GCN_V_CMPSX_NLT_F32_E64:
		return "v_cmpsx_nlt_f32";
	case GCN_V_CMPSX_TRU_F32_E64:
		return "v_cmpsx_tru_f32";
	case GCN_V_CMPS_F_F64_E64:
		return "v_cmps_f_f64";
	case GCN_V_CMPS_LT_F64_E64:
		return "v_cmps_lt_f64";
	case GCN_V_CMPS_EQ_F64_E64:
		return "v_cmps_eq_f64";
	case GCN_V_CMPS_LE_F64_E64:
		return "v_cmps_le_f64";
	case GCN_V_CMPS_GT_F64_E64:
		return "v_cmps_gt_f64";
	case GCN_V_CMPS_LG_F64_E64:
		return "v_cmps_lg_f64";
	case GCN_V_CMPS_GE_F64_E64:
		return "v_cmps_ge_f64";
	case GCN_V_CMPS_O_F64_E64:
		return "v_cmps_o_f64";
	case GCN_V_CMPS_U_F64_E64:
		return "v_cmps_u_f64";
	case GCN_V_CMPS_NGE_F64_E64:
		return "v_cmps_nge_f64";
	case GCN_V_CMPS_NLG_F64_E64:
		return "v_cmps_nlg_f64";
	case GCN_V_CMPS_NGT_F64_E64:
		return "v_cmps_ngt_f64";
	case GCN_V_CMPS_NLE_F64_E64:
		return "v_cmps_nle_f64";
	case GCN_V_CMPS_NEQ_F64_E64:
		return "v_cmps_neq_f64";
	case GCN_V_CMPS_NLT_F64_E64:
		return "v_cmps_nlt_f64";
	case GCN_V_CMPS_TRU_F64_E64:
		return "v_cmps_tru_f64";
	case GCN_V_CMPSX_F_F64_E64:
		return "v_cmpsx_f_f64";
	case GCN_V_CMPSX_LT_F64_E64:
		return "v_cmpsx_lt_f64";
	case GCN_V_CMPSX_EQ_F64_E64:
		return "v_cmpsx_eq_f64";
	case GCN_V_CMPSX_LE_F64_E64:
		return "v_cmpsx_le_f64";
	case GCN_V_CMPSX_GT_F64_E64:
		return "v_cmpsx_gt_f64";
	case GCN_V_CMPSX_LG_F64_E64:
		return "v_cmpsx_lg_f64";
	case GCN_V_CMPSX_GE_F64_E64:
		return "v_cmpsx_ge_f64";
	case GCN_V_CMPSX_O_F64_E64:
		return "v_cmpsx_o_f64";
	case GCN_V_CMPSX_U_F64_E64:
		return "v_cmpsx_u_f64";
	case GCN_V_CMPSX_NGE_F64_E64:
		return "v_cmpsx_nge_f64";
	case GCN_V_CMPSX_NLG_F64_E64:
		return "v_cmpsx_nlg_f64";
	case GCN_V_CMPSX_NGT_F64_E64:
		return "v_cmpsx_ngt_f64";
	case GCN_V_CMPSX_NLE_F64_E64:
		return "v_cmpsx_nle_f64";
	case GCN_V_CMPSX_NEQ_F64_E64:
		return "v_cmpsx_neq_f64";
	case GCN_V_CMPSX_NLT_F64_E64:
		return "v_cmpsx_nlt_f64";
	case GCN_V_CMPSX_TRU_F64_E64:
		return "v_cmpsx_tru_f64";
	case GCN_V_CMP_F_I32_E64:
		return "v_cmp_f_i32";
	case GCN_V_CMP_LT_I32_E64:
		return "v_cmp_lt_i32";
	case GCN_V_CMP_EQ_I32_E64:
		return "v_cmp_eq_i32";
	case GCN_V_CMP_LE_I32_E64:
		return "v_cmp_le_i32";
	case GCN_V_CMP_GT_I32_E64:
		return "v_cmp_gt_i32";
	case GCN_V_CMP_LG_I32_E64:
		return "v_cmp_lg_i32";
	case GCN_V_CMP_GE_I32_E64:
		return "v_cmp_ge_i32";
	case GCN_V_CMP_TRU_I32_E64:
		return "v_cmp_tru_i32";
	case GCN_V_CMP_CLASS_F32_E64:
		return "v_cmp_class_f32";
	case GCN_V_CMPX_F_I32_E64:
		return "v_cmpx_f_i32";
	case GCN_V_CMPX_LT_I32_E64:
		return "v_cmpx_lt_i32";
	case GCN_V_CMPX_EQ_I32_E64:
		return "v_cmpx_eq_i32";
	case GCN_V_CMPX_LE_I32_E64:
		return "v_cmpx_le_i32";
	case GCN_V_CMPX_GT_I32_E64:
		return "v_cmpx_gt_i32";
	case GCN_V_CMPX_LG_I32_E64:
		return "v_cmpx_lg_i32";
	case GCN_V_CMPX_GE_I32_E64:
		return "v_cmpx_ge_i32";
	case GCN_V_CMPX_TRU_I32_E64:
		return "v_cmpx_tru_i32";
	case GCN_V_CMPX_CLASS_F32_E64:
		return "v_cmpx_class_f32";
	case GCN_V_CMP_F_I64_E64:
		return "v_cmp_f_i64";
	case GCN_V_CMP_LT_I64_E64:
		return "v_cmp_lt_i64";
	case GCN_V_CMP_EQ_I64_E64:
		return "v_cmp_eq_i64";
	case GCN_V_CMP_LE_I64_E64:
		return "v_cmp_le_i64";
	case GCN_V_CMP_GT_I64_E64:
		return "v_cmp_gt_i64";
	case GCN_V_CMP_LG_I64_E64:
		return "v_cmp_lg_i64";
	case GCN_V_CMP_GE_I64_E64:
		return "v_cmp_ge_i64";
	case GCN_V_CMP_TRU_I64_E64:
		return "v_cmp_tru_i64";
	case GCN_V_CMP_CLASS_F64_E64:
		return "v_cmp_class_f64";
	case GCN_V_CMPX_F_I64_E64:
		return "v_cmpx_f_i64";
	case GCN_V_CMPX_LT_I64_E64:
		return "v_cmpx_lt_i64";
	case GCN_V_CMPX_EQ_I64_E64:
		return "v_cmpx_eq_i64";
	case GCN_V_CMPX_LE_I64_E64:
		return "v_cmpx_le_i64";
	case GCN_V_CMPX_GT_I64_E64:
		return "v_cmpx_gt_i64";
	case GCN_V_CMPX_LG_I64_E64:
		return "v_cmpx_lg_i64";
	case GCN_V_CMPX_GE_I64_E64:
		return "v_cmpx_ge_i64";
	case GCN_V_CMPX_TRU_I64_E64:
		return "v_cmpx_tru_i64";
	case GCN_V_CMPX_CLASS_F64_E64:
		return "v_cmpx_class_f64";
	case GCN_V_CMP_F_U32_E64:
		return "v_cmp_f_u32";
	case GCN_V_CMP_LT_U32_E64:
		return "v_cmp_lt_u32";
	case GCN_V_CMP_EQ_U32_E64:
		return "v_cmp_eq_u32";
	case GCN_V_CMP_LE_U32_E64:
		return "v_cmp_le_u32";
	case GCN_V_CMP_GT_U32_E64:
		return "v_cmp_gt_u32";
	case GCN_V_CMP_LG_U32_E64:
		return "v_cmp_lg_u32";
	case GCN_V_CMP_GE_U32_E64:
		return "v_cmp_ge_u32";
	case GCN_V_CMP_TRU_U32_E64:
		return "v_cmp_tru_u32";
	case GCN_V_CMPX_F_U32_E64:
		return "v_cmpx_f_u32";
	case GCN_V_CMPX_LT_U32_E64:
		return "v_cmpx_lt_u32";
	case GCN_V_CMPX_EQ_U32_E64:
		return "v_cmpx_eq_u32";
	case GCN_V_CMPX_LE_U32_E64:
		return "v_cmpx_le_u32";
	case GCN_V_CMPX_GT_U32_E64:
		return "v_cmpx_gt_u32";
	case GCN_V_CMPX_LG_U32_E64:
		return "v_cmpx_lg_u32";
	case GCN_V_CMPX_GE_U32_E64:
		return "v_cmpx_ge_u32";
	case GCN_V_CMPX_TRU_U32_E64:
		return "v_cmpx_tru_u32";
	case GCN_V_CMP_F_U64_E64:
		return "v_cmp_f_u64";
	case GCN_V_CMP_LT_U64_E64:
		return "v_cmp_lt_u64";
	case GCN_V_CMP_EQ_U64_E64:
		return "v_cmp_eq_u64";
	case GCN_V_CMP_LE_U64_E64:
		return "v_cmp_le_u64";
	case GCN_V_CMP_GT_U64_E64:
		return "v_cmp_gt_u64";
	case GCN_V_CMP_LG_U64_E64:
		return "v_cmp_lg_u64";
	case GCN_V_CMP_GE_U64_E64:
		return "v_cmp_ge_u64";
	case GCN_V_CMP_TRU_U64_E64:
		return "v_cmp_tru_u64";
	case GCN_V_CMPX_F_U64_E64:
		return "v_cmpx_f_u64";
	case GCN_V_CMPX_LT_U64_E64:
		return "v_cmpx_lt_u64";
	case GCN_V_CMPX_EQ_U64_E64:
		return "v_cmpx_eq_u64";
	case GCN_V_CMPX_LE_U64_E64:
		return "v_cmpx_le_u64";
	case GCN_V_CMPX_GT_U64_E64:
		return "v_cmpx_gt_u64";
	case GCN_V_CMPX_LG_U64_E64:
		return "v_cmpx_lg_u64";
	case GCN_V_CMPX_GE_U64_E64:
		return "v_cmpx_ge_u64";
	case GCN_V_CMPX_TRU_U64_E64:
		return "v_cmpx_tru_u64";
	case GCN_V_CNDMASK_B32_E64:
		return "v_cndmask_b32";
	case GCN_V_READLANE_B32_E64:
		return "v_readlane_b32";
	case GCN_V_WRITELANE_B32_E64:
		return "v_writelane_b32";
	case GCN_V_ADD_F32_E64:
		return "v_add_f32";
	case GCN_V_SUB_F32_E64:
		return "v_sub_f32";
	case GCN_V_SUBREV_F32_E64:
		return "v_subrev_f32";
	case GCN_V_MAC_LEGACY_F32_E64:
		return "v_mac_legacy_f32";
	case GCN_V_MUL_LEGACY_F32_E64:
		return "v_mul_legacy_f32";
	case GCN_V_MUL_F32_E64:
		return "v_mul_f32";
	case GCN_V_MUL_I32_I24_E64:
		return "v_mul_i32_i24";
	case GCN_V_MUL_HI_I32_I24_E64:
		return "v_mul_hi_i32_i24";
	case GCN_V_MUL_U32_U24_E64:
		return "v_mul_u32_u24";
	case GCN_V_MUL_HI_U32_U24_E64:
		return "v_mul_hi_u32_u24";
	case GCN_V_MIN_LEGACY_F32_E64:
		return "v_min_legacy_f32";
	case GCN_V_MAX_LEGACY_F32_E64:
		return "v_max_legacy_f32";
	case GCN_V_MIN_F32_E64:
		return "v_min_f32";
	case GCN_V_MAX_F32_E64:
		return "v_max_f32";
	case GCN_V_MIN_I32_E64:
		return "v_min_i32";
	case GCN_V_MAX_I32_E64:
		return "v_max_i32";
	case GCN_V_MIN_U32_E64:
		return "v_min_u32";
	case GCN_V_MAX_U32_E64:
		return "v_max_u32";
	case GCN_V_LSHR_B32_E64:
		return "v_lshr_b32";
	case GCN_V_LSHRREV_B32_E64:
		return "v_lshrrev_b32";
	case GCN_V_ASHR_I32_E64:
		return "v_ashr_i32";
	case GCN_V_ASHRREV_I32_E64:
		return "v_ashrrev_i32";
	case GCN_V_LSHL_B32_E64:
		return "v_lshl_b32";
	case GCN_V_LSHLREV_B32_E64:
		return "v_lshlrev_b32";
	case GCN_V_AND_B32_E64:
		return "v_and_b32";
	case GCN_V_OR_B32_E64:
		return "v_or_b32";
	case GCN_V_XOR_B32_E64:
		return "v_xor_b32";
	case GCN_V_BFM_B32_E64:
		return "v_bfm_b32";
	case GCN_V_MAC_F32_E64:
		return "v_mac_f32";
	case GCN_V_MADMK_F32_E64:
		return "v_madmk_f32";
	case GCN_V_MADAK_F32_E64:
		return "v_madak_f32";
	case GCN_V_BCNT_U32_B32_E64:
		return "v_bcnt_u32_b32";
	case GCN_V_MBCNT_LO_U32_B32_E64:
		return "v_mbcnt_lo_u32_b32";
	case GCN_V_MBCNT_HI_U32_B32_E64:
		return "v_mbcnt_hi_u32_b32";
	case GCN_V_ADD_I32_E64:
		return "v_add_i32";
	case GCN_V_SUB_I32_E64:
		return "v_sub_i32";
	case GCN_V_SUBREV_I32_E64:
		return "v_subrev_i32";
	case GCN_V_ADDC_U32_E64:
		return "v_addc_u32";
	case GCN_V_SUBB_U32_E64:
		return "v_subb_u32";
	case GCN_V_SUBBREV_U32_E64:
		return "v_subbrev_u32";
	case GCN_V_LDEXP_F32_E64:
		return "v_ldexp_f32";
	case GCN_V_CVT_PKACCUM_U8_F32_E64:
		return "v_cvt_pkaccum_u8_f32";
	case GCN_V_CVT_PKNORM_I16_F32_E64:
		return "v_cvt_pknorm_i16_f32";
	case GCN_V_CVT_PKNORM_U16_F32_E64:
		return "v_cvt_pknorm_u16_f32";
	case GCN_V_CVT_PKRTZ_F16_F32_E64:
		return "v_cvt_pkrtz_f16_f32";
	case GCN_V_CVT_PK_U16_U32_E64:
		return "v_cvt_pk_u16_u32";
	case GCN_V_CVT_PK_I16_I32_E64:
		return "v_cvt_pk_i16_i32";
	case GCN_V_MAD_LEGACY_F32_E64:
		return "v_mad_legacy_f32";
	case GCN_V_MAD_F32_E64:
		return "v_mad_f32";
	case GCN_V_MAD_I32_I24_E64:
		return "v_mad_i32_i24";
	case GCN_V_MAD_U32_U24_E64:
		return "v_mad_u32_u24";
	case GCN_V_CUBEID_F32_E64:
		return "v_cubeid_f32";
	case GCN_V_CUBESC_F32_E64:
		return "v_cubesc_f32";
	case GCN_V_CUBETC_F32_E64:
		return "v_cubetc_f32";
	case GCN_V_CUBEMA_F32_E64:
		return "v_cubema_f32";
	case GCN_V_BFE_U32_E64:
		return "v_bfe_u32";
	case GCN_V_BFE_I32_E64:
		return "v_bfe_i32";
	case GCN_V_BFI_B32_E64:
		return "v_bfi_b32";
	case GCN_V_FMA_F32_E64:
		return "v_fma_f32";
	case GCN_V_FMA_F64_E64:
		return "v_fma_f64";
	case GCN_V_LERP_U8_E64:
		return "v_lerp_u8";
	case GCN_V_ALIGNBIT_B32_E64:
		return "v_alignbit_b32";
	case GCN_V_ALIGNBYTE_B32_E64:
		return "v_alignbyte_b32";
	case GCN_V_MULLIT_F32_E64:
		return "v_mullit_f32";
	case GCN_V_MIN3_F32_E64:
		return "v_min3_f32";
	case GCN_V_MIN3_I32_E64:
		return "v_min3_i32";
	case GCN_V_MIN3_U32_E64:
		return "v_min3_u32";
	case GCN_V_MAX3_F32_E64:
		return "v_max3_f32";
	case GCN_V_MAX3_I32_E64:
		return "v_max3_i32";
	case GCN_V_MAX3_U32_E64:
		return "v_max3_u32";
	case GCN_V_MED3_F32_E64:
		return "v_med3_f32";
	case GCN_V_MED3_I32_E64:
		return "v_med3_i32";
	case GCN_V_MED3_U32_E64:
		return "v_med3_u32";
	case GCN_V_SAD_U8_E64:
		return "v_sad_u8";
	case GCN_V_SAD_HI_U8_E64:
		return "v_sad_hi_u8";
	case GCN_V_SAD_U16_E64:
		return "v_sad_u16";
	case GCN_V_SAD_U32_E64:
		return "v_sad_u32";
	case GCN_V_CVT_PK_U8_F32_E64:
		return "v_cvt_pk_u8_f32";
	case GCN_V_DIV_FIXUP_F32_E64:
		return "v_div_fixup_f32";
	case GCN_V_DIV_FIXUP_F64_E64:
		return "v_div_fixup_f64";
	case GCN_V_LSHL_B64_E64:
		return "v_lshl_b64";
	case GCN_V_LSHR_B64_E64:
		return "v_lshr_b64";
	case GCN_V_ASHR_I64_E64:
		return "v_ashr_i64";
	case GCN_V_ADD_F64_E64:
		return "v_add_f64";
	case GCN_V_MUL_F64_E64:
		return "v_mul_f64";
	case GCN_V_MIN_F64_E64:
		return "v_min_f64";
	case GCN_V_MAX_F64_E64:
		return "v_max_f64";
	case GCN_V_LDEXP_F64_E64:
		return "v_ldexp_f64";
	case GCN_V_MUL_LO_U32_E64:
		return "v_mul_lo_u32";
	case GCN_V_MUL_HI_U32_E64:
		return "v_mul_hi_u32";
	case GCN_V_MUL_LO_I32_E64:
		return "v_mul_lo_i32";
	case GCN_V_MUL_HI_I32_E64:
		return "v_mul_hi_i32";
	case GCN_V_DIV_SCALE_F32_E64:
		return "v_div_scale_f32";
	case GCN_V_DIV_SCALE_F64_E64:
		return "v_div_scale_f64";
	case GCN_V_DIV_FMAS_F32_E64:
		return "v_div_fmas_f32";
	case GCN_V_DIV_FMAS_F64_E64:
		return "v_div_fmas_f64";
	case GCN_V_MSAD_U8_E64:
		return "v_msad_u8";
	case GCN_V_QSAD_PK_U16_U8_E64:
		return "v_qsad_pk_u16_u8";
	case GCN_V_MQSAD_PK_U16_U8_E64:
		return "v_mqsad_pk_u16_u8";
	case GCN_V_TRIG_PREOP_F64_E64:
		return "v_trig_preop_f64";
	case GCN_V_MQSAD_U32_U8_E64:
		return "v_mqsad_u32_u8";
	case GCN_V_MAD_U64_U32_E64:
		return "v_mad_u64_u32";
	case GCN_V_MAD_I64_I32_E64:
		return "v_mad_i64_i32";
	case GCN_V_NOP_E64:
		return "v_nop";
	case GCN_V_MOV_B32_E64:
		return "v_mov_b32";
	case GCN_V_READFIRSTLANE_B32_E64:
		return "v_readfirstlane_b32";
	case GCN_V_CVT_I32_F64_E64:
		return "v_cvt_i32_f64";
	case GCN_V_CVT_F64_I32_E64:
		return "v_cvt_f64_i32";
	case GCN_V_CVT_F32_I32_E64:
		return "v_cvt_f32_i32";
	case GCN_V_CVT_F32_U32_E64:
		return "v_cvt_f32_u32";
	case GCN_V_CVT_U32_F32_E64:
		return "v_cvt_u32_f32";
	case GCN_V_CVT_I32_F32_E64:
		return "v_cvt_i32_f32";
	case GCN_V_MOV_FED_B32_E64:
		return "v_mov_fed_b32";
	case GCN_V_CVT_F16_F32_E64:
		return "v_cvt_f16_f32";
	case GCN_V_CVT_F32_F16_E64:
		return "v_cvt_f32_f16";
	case GCN_V_CVT_RPI_I32_F32_E64:
		return "v_cvt_rpi_i32_f32";
	case GCN_V_CVT_FLR_I32_F32_E64:
		return "v_cvt_flr_i32_f32";
	case GCN_V_CVT_OFF_F32_I4_E64:
		return "v_cvt_off_f32_i4";
	case GCN_V_CVT_F32_F64_E64:
		return "v_cvt_f32_f64";
	case GCN_V_CVT_F64_F32_E64:
		return "v_cvt_f64_f32";
	case GCN_V_CVT_F32_UBYTE0_E64:
		return "v_cvt_f32_ubyte0";
	case GCN_V_CVT_F32_UBYTE1_E64:
		return "v_cvt_f32_ubyte1";
	case GCN_V_CVT_F32_UBYTE2_E64:
		return "v_cvt_f32_ubyte2";
	case GCN_V_CVT_F32_UBYTE3_E64:
		return "v_cvt_f32_ubyte3";
	case GCN_V_CVT_U32_F64_E64:
		return "v_cvt_u32_f64";
	case GCN_V_CVT_F64_U32_E64:
		return "v_cvt_f64_u32";
	case GCN_V_TRUNC_F64_E64:
		return "v_trunc_f64";
	case GCN_V_CEIL_F64_E64:
		return "v_ceil_f64";
	case GCN_V_RNDNE_F64_E64:
		return "v_rndne_f64";
	case GCN_V_FLOOR_F64_E64:
		return "v_floor_f64";
	case GCN_V_FRACT_F32_E64:
		return "v_fract_f32";
	case GCN_V_TRUNC_F32_E64:
		return "v_trunc_f32";
	case GCN_V_CEIL_F32_E64:
		return "v_ceil_f32";
	case GCN_V_RNDNE_F32_E64:
		return "v_rndne_f32";
	case GCN_V_FLOOR_F32_E64:
		return "v_floor_f32";
	case GCN_V_EXP_F32_E64:
		return "v_exp_f32";
	case GCN_V_LOG_CLAMP_F32_E64:
		return "v_log_clamp_f32";
	case GCN_V_LOG_F32_E64:
		return "v_log_f32";
	case GCN_V_RCP_CLAMP_F32_E64:
		return "v_rcp_clamp_f32";
	case GCN_V_RCP_LEGACY_F32_E64:
		return "v_rcp_legacy_f32";
	case GCN_V_RCP_F32_E64:
		return "v_rcp_f32";
	case GCN_V_RCP_IFLAG_F32_E64:
		return "v_rcp_iflag_f32";
	case GCN_V_RSQ_CLAMP_F32_E64:
		return "v_rsq_clamp_f32";
	case GCN_V_RSQ_LEGACY_F32_E64:
		return "v_rsq_legacy_f32";
	case GCN_V_RSQ_F32_E64:
		return "v_rsq_f32";
	case GCN_V_RCP_F64_E64:
		return "v_rcp_f64";
	case GCN_V_RCP_CLAMP_F64_E64:
		return "v_rcp_clamp_f64";
	case GCN_V_RSQ_F64_E64:
		return "v_rsq_f64";
	case GCN_V_RSQ_CLAMP_F64_E64:
		return "v_rsq_clamp_f64";
	case GCN_V_SQRT_F32_E64:
		return "v_sqrt_f32";
	case GCN_V_SQRT_F64_E64:
		return "v_sqrt_f64";
	case GCN_V_SIN_F32_E64:
		return "v_sin_f32";
	case GCN_V_COS_F32_E64:
		return "v_cos_f32";
	case GCN_V_NOT_B32_E64:
		return "v_not_b32";
	case GCN_V_BFREV_B32_E64:
		return "v_bfrev_b32";
	case GCN_V_FFBH_U32_E64:
		return "v_ffbh_u32";
	case GCN_V_FFBL_B32_E64:
		return "v_ffbl_b32";
	case GCN_V_FFBH_I32_E64:
		return "v_ffbh_i32";
	case GCN_V_FREXP_EXP_I32_F64_E64:
		return "v_frexp_exp_i32_f64";
	case GCN_V_FREXP_MANT_F64_E64:
		return "v_frexp_mant_f64";
	case GCN_V_FRACT_F64_E64:
		return "v_fract_f64";
	case GCN_V_FREXP_EXP_I32_F32_E64:
		return "v_frexp_exp_i32_f32";
	case GCN_V_FREXP_MANT_F32_E64:
		return "v_frexp_mant_f32";
	case GCN_V_CLREXCP_E64:
		return "v_clrexcp";
	case GCN_V_MOVRELD_B32_E64:
		return "v_movreld_b32";
	case GCN_V_MOVRELS_B32_E64:
		return "v_movrels_b32";
	case GCN_V_MOVRELSD_B32_E64:
		return "v_movrelsd_b32";
	case GCN_V_LOG_LEGACY_F32_E64:
		return "v_log_legacy_f32";
	case GCN_V_EXP_LEGACY_F32_E64:
		return "v_exp_legacy_f32";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrOpcodeVOPC(GcnOpcodeVOPC op) {
	switch (op) {
	case GCN_V_CMP_F_F32:
		return "v_cmp_f_f32";
	case GCN_V_CMP_LT_F32:
		return "v_cmp_lt_f32";
	case GCN_V_CMP_EQ_F32:
		return "v_cmp_eq_f32";
	case GCN_V_CMP_LE_F32:
		return "v_cmp_le_f32";
	case GCN_V_CMP_GT_F32:
		return "v_cmp_gt_f32";
	case GCN_V_CMP_LG_F32:
		return "v_cmp_lg_f32";
	case GCN_V_CMP_GE_F32:
		return "v_cmp_ge_f32";
	case GCN_V_CMP_O_F32:
		return "v_cmp_o_f32";
	case GCN_V_CMP_U_F32:
		return "v_cmp_u_f32";
	case GCN_V_CMP_NGE_F32:
		return "v_cmp_nge_f32";
	case GCN_V_CMP_NLG_F32:
		return "v_cmp_nlg_f32";
	case GCN_V_CMP_NGT_F32:
		return "v_cmp_ngt_f32";
	case GCN_V_CMP_NLE_F32:
		return "v_cmp_nle_f32";
	case GCN_V_CMP_NEQ_F32:
		return "v_cmp_neq_f32";
	case GCN_V_CMP_NLT_F32:
		return "v_cmp_nlt_f32";
	case GCN_V_CMP_TRU_F32:
		return "v_cmp_tru_f32";
	case GCN_V_CMPX_F_F32:
		return "v_cmpx_f_f32";
	case GCN_V_CMPX_LT_F32:
		return "v_cmpx_lt_f32";
	case GCN_V_CMPX_EQ_F32:
		return "v_cmpx_eq_f32";
	case GCN_V_CMPX_LE_F32:
		return "v_cmpx_le_f32";
	case GCN_V_CMPX_GT_F32:
		return "v_cmpx_gt_f32";
	case GCN_V_CMPX_LG_F32:
		return "v_cmpx_lg_f32";
	case GCN_V_CMPX_GE_F32:
		return "v_cmpx_ge_f32";
	case GCN_V_CMPX_O_F32:
		return "v_cmpx_o_f32";
	case GCN_V_CMPX_U_F32:
		return "v_cmpx_u_f32";
	case GCN_V_CMPX_NGE_F32:
		return "v_cmpx_nge_f32";
	case GCN_V_CMPX_NLG_F32:
		return "v_cmpx_nlg_f32";
	case GCN_V_CMPX_NGT_F32:
		return "v_cmpx_ngt_f32";
	case GCN_V_CMPX_NLE_F32:
		return "v_cmpx_nle_f32";
	case GCN_V_CMPX_NEQ_F32:
		return "v_cmpx_neq_f32";
	case GCN_V_CMPX_NLT_F32:
		return "v_cmpx_nlt_f32";
	case GCN_V_CMPX_TRU_F32:
		return "v_cmpx_tru_f32";
	case GCN_V_CMP_F_F64:
		return "v_cmp_f_f64";
	case GCN_V_CMP_LT_F64:
		return "v_cmp_lt_f64";
	case GCN_V_CMP_EQ_F64:
		return "v_cmp_eq_f64";
	case GCN_V_CMP_LE_F64:
		return "v_cmp_le_f64";
	case GCN_V_CMP_GT_F64:
		return "v_cmp_gt_f64";
	case GCN_V_CMP_LG_F64:
		return "v_cmp_lg_f64";
	case GCN_V_CMP_GE_F64:
		return "v_cmp_ge_f64";
	case GCN_V_CMP_O_F64:
		return "v_cmp_o_f64";
	case GCN_V_CMP_U_F64:
		return "v_cmp_u_f64";
	case GCN_V_CMP_NGE_F64:
		return "v_cmp_nge_f64";
	case GCN_V_CMP_NLG_F64:
		return "v_cmp_nlg_f64";
	case GCN_V_CMP_NGT_F64:
		return "v_cmp_ngt_f64";
	case GCN_V_CMP_NLE_F64:
		return "v_cmp_nle_f64";
	case GCN_V_CMP_NEQ_F64:
		return "v_cmp_neq_f64";
	case GCN_V_CMP_NLT_F64:
		return "v_cmp_nlt_f64";
	case GCN_V_CMP_TRU_F64:
		return "v_cmp_tru_f64";
	case GCN_V_CMPX_F_F64:
		return "v_cmpx_f_f64";
	case GCN_V_CMPX_LT_F64:
		return "v_cmpx_lt_f64";
	case GCN_V_CMPX_EQ_F64:
		return "v_cmpx_eq_f64";
	case GCN_V_CMPX_LE_F64:
		return "v_cmpx_le_f64";
	case GCN_V_CMPX_GT_F64:
		return "v_cmpx_gt_f64";
	case GCN_V_CMPX_LG_F64:
		return "v_cmpx_lg_f64";
	case GCN_V_CMPX_GE_F64:
		return "v_cmpx_ge_f64";
	case GCN_V_CMPX_O_F64:
		return "v_cmpx_o_f64";
	case GCN_V_CMPX_U_F64:
		return "v_cmpx_u_f64";
	case GCN_V_CMPX_NGE_F64:
		return "v_cmpx_nge_f64";
	case GCN_V_CMPX_NLG_F64:
		return "v_cmpx_nlg_f64";
	case GCN_V_CMPX_NGT_F64:
		return "v_cmpx_ngt_f64";
	case GCN_V_CMPX_NLE_F64:
		return "v_cmpx_nle_f64";
	case GCN_V_CMPX_NEQ_F64:
		return "v_cmpx_neq_f64";
	case GCN_V_CMPX_NLT_F64:
		return "v_cmpx_nlt_f64";
	case GCN_V_CMPX_TRU_F64:
		return "v_cmpx_tru_f64";
	case GCN_V_CMPS_F_F32:
		return "v_cmps_f_f32";
	case GCN_V_CMPS_LT_F32:
		return "v_cmps_lt_f32";
	case GCN_V_CMPS_EQ_F32:
		return "v_cmps_eq_f32";
	case GCN_V_CMPS_LE_F32:
		return "v_cmps_le_f32";
	case GCN_V_CMPS_GT_F32:
		return "v_cmps_gt_f32";
	case GCN_V_CMPS_LG_F32:
		return "v_cmps_lg_f32";
	case GCN_V_CMPS_GE_F32:
		return "v_cmps_ge_f32";
	case GCN_V_CMPS_O_F32:
		return "v_cmps_o_f32";
	case GCN_V_CMPS_U_F32:
		return "v_cmps_u_f32";
	case GCN_V_CMPS_NGE_F32:
		return "v_cmps_nge_f32";
	case GCN_V_CMPS_NLG_F32:
		return "v_cmps_nlg_f32";
	case GCN_V_CMPS_NGT_F32:
		return "v_cmps_ngt_f32";
	case GCN_V_CMPS_NLE_F32:
		return "v_cmps_nle_f32";
	case GCN_V_CMPS_NEQ_F32:
		return "v_cmps_neq_f32";
	case GCN_V_CMPS_NLT_F32:
		return "v_cmps_nlt_f32";
	case GCN_V_CMPS_TRU_F32:
		return "v_cmps_tru_f32";
	case GCN_V_CMPSX_F_F32:
		return "v_cmpsx_f_f32";
	case GCN_V_CMPSX_LT_F32:
		return "v_cmpsx_lt_f32";
	case GCN_V_CMPSX_EQ_F32:
		return "v_cmpsx_eq_f32";
	case GCN_V_CMPSX_LE_F32:
		return "v_cmpsx_le_f32";
	case GCN_V_CMPSX_GT_F32:
		return "v_cmpsx_gt_f32";
	case GCN_V_CMPSX_LG_F32:
		return "v_cmpsx_lg_f32";
	case GCN_V_CMPSX_GE_F32:
		return "v_cmpsx_ge_f32";
	case GCN_V_CMPSX_O_F32:
		return "v_cmpsx_o_f32";
	case GCN_V_CMPSX_U_F32:
		return "v_cmpsx_u_f32";
	case GCN_V_CMPSX_NGE_F32:
		return "v_cmpsx_nge_f32";
	case GCN_V_CMPSX_NLG_F32:
		return "v_cmpsx_nlg_f32";
	case GCN_V_CMPSX_NGT_F32:
		return "v_cmpsx_ngt_f32";
	case GCN_V_CMPSX_NLE_F32:
		return "v_cmpsx_nle_f32";
	case GCN_V_CMPSX_NEQ_F32:
		return "v_cmpsx_neq_f32";
	case GCN_V_CMPSX_NLT_F32:
		return "v_cmpsx_nlt_f32";
	case GCN_V_CMPSX_TRU_F32:
		return "v_cmpsx_tru_f32";
	case GCN_V_CMPS_F_F64:
		return "v_cmps_f_f64";
	case GCN_V_CMPS_LT_F64:
		return "v_cmps_lt_f64";
	case GCN_V_CMPS_EQ_F64:
		return "v_cmps_eq_f64";
	case GCN_V_CMPS_LE_F64:
		return "v_cmps_le_f64";
	case GCN_V_CMPS_GT_F64:
		return "v_cmps_gt_f64";
	case GCN_V_CMPS_LG_F64:
		return "v_cmps_lg_f64";
	case GCN_V_CMPS_GE_F64:
		return "v_cmps_ge_f64";
	case GCN_V_CMPS_O_F64:
		return "v_cmps_o_f64";
	case GCN_V_CMPS_U_F64:
		return "v_cmps_u_f64";
	case GCN_V_CMPS_NGE_F64:
		return "v_cmps_nge_f64";
	case GCN_V_CMPS_NLG_F64:
		return "v_cmps_nlg_f64";
	case GCN_V_CMPS_NGT_F64:
		return "v_cmps_ngt_f64";
	case GCN_V_CMPS_NLE_F64:
		return "v_cmps_nle_f64";
	case GCN_V_CMPS_NEQ_F64:
		return "v_cmps_neq_f64";
	case GCN_V_CMPS_NLT_F64:
		return "v_cmps_nlt_f64";
	case GCN_V_CMPS_TRU_F64:
		return "v_cmps_tru_f64";
	case GCN_V_CMPSX_F_F64:
		return "v_cmpsx_f_f64";
	case GCN_V_CMPSX_LT_F64:
		return "v_cmpsx_lt_f64";
	case GCN_V_CMPSX_EQ_F64:
		return "v_cmpsx_eq_f64";
	case GCN_V_CMPSX_LE_F64:
		return "v_cmpsx_le_f64";
	case GCN_V_CMPSX_GT_F64:
		return "v_cmpsx_gt_f64";
	case GCN_V_CMPSX_LG_F64:
		return "v_cmpsx_lg_f64";
	case GCN_V_CMPSX_GE_F64:
		return "v_cmpsx_ge_f64";
	case GCN_V_CMPSX_O_F64:
		return "v_cmpsx_o_f64";
	case GCN_V_CMPSX_U_F64:
		return "v_cmpsx_u_f64";
	case GCN_V_CMPSX_NGE_F64:
		return "v_cmpsx_nge_f64";
	case GCN_V_CMPSX_NLG_F64:
		return "v_cmpsx_nlg_f64";
	case GCN_V_CMPSX_NGT_F64:
		return "v_cmpsx_ngt_f64";
	case GCN_V_CMPSX_NLE_F64:
		return "v_cmpsx_nle_f64";
	case GCN_V_CMPSX_NEQ_F64:
		return "v_cmpsx_neq_f64";
	case GCN_V_CMPSX_NLT_F64:
		return "v_cmpsx_nlt_f64";
	case GCN_V_CMPSX_TRU_F64:
		return "v_cmpsx_tru_f64";
	case GCN_V_CMP_F_I32:
		return "v_cmp_f_i32";
	case GCN_V_CMP_LT_I32:
		return "v_cmp_lt_i32";
	case GCN_V_CMP_EQ_I32:
		return "v_cmp_eq_i32";
	case GCN_V_CMP_LE_I32:
		return "v_cmp_le_i32";
	case GCN_V_CMP_GT_I32:
		return "v_cmp_gt_i32";
	case GCN_V_CMP_NE_I32:
		return "v_cmp_ne_i32";
	case GCN_V_CMP_GE_I32:
		return "v_cmp_ge_i32";
	case GCN_V_CMP_TRU_I32:
		return "v_cmp_tru_i32";
	case GCN_V_CMP_CLASS_F32:
		return "v_cmp_class_f32";
	case GCN_V_CMPX_F_I32:
		return "v_cmpx_f_i32";
	case GCN_V_CMPX_LT_I32:
		return "v_cmpx_lt_i32";
	case GCN_V_CMPX_EQ_I32:
		return "v_cmpx_eq_i32";
	case GCN_V_CMPX_LE_I32:
		return "v_cmpx_le_i32";
	case GCN_V_CMPX_GT_I32:
		return "v_cmpx_gt_i32";
	case GCN_V_CMPX_NE_I32:
		return "v_cmpx_ne_i32";
	case GCN_V_CMPX_GE_I32:
		return "v_cmpx_ge_i32";
	case GCN_V_CMPX_TRU_I32:
		return "v_cmpx_tru_i32";
	case GCN_V_CMPX_CLASS_F32:
		return "v_cmpx_class_f32";
	case GCN_V_CMP_F_I64:
		return "v_cmp_f_i64";
	case GCN_V_CMP_LT_I64:
		return "v_cmp_lt_i64";
	case GCN_V_CMP_EQ_I64:
		return "v_cmp_eq_i64";
	case GCN_V_CMP_LE_I64:
		return "v_cmp_le_i64";
	case GCN_V_CMP_GT_I64:
		return "v_cmp_gt_i64";
	case GCN_V_CMP_NE_I64:
		return "v_cmp_ne_i64";
	case GCN_V_CMP_GE_I64:
		return "v_cmp_ge_i64";
	case GCN_V_CMP_TRU_I64:
		return "v_cmp_tru_i64";
	case GCN_V_CMP_CLASS_F64:
		return "v_cmp_class_f64";
	case GCN_V_CMPX_F_I64:
		return "v_cmpx_f_i64";
	case GCN_V_CMPX_LT_I64:
		return "v_cmpx_lt_i64";
	case GCN_V_CMPX_EQ_I64:
		return "v_cmpx_eq_i64";
	case GCN_V_CMPX_LE_I64:
		return "v_cmpx_le_i64";
	case GCN_V_CMPX_GT_I64:
		return "v_cmpx_gt_i64";
	case GCN_V_CMPX_NE_I64:
		return "v_cmpx_ne_i64";
	case GCN_V_CMPX_GE_I64:
		return "v_cmpx_ge_i64";
	case GCN_V_CMPX_TRU_I64:
		return "v_cmpx_tru_i64";
	case GCN_V_CMPX_CLASS_F64:
		return "v_cmpx_class_f64";
	case GCN_V_CMP_F_U32:
		return "v_cmp_f_u32";
	case GCN_V_CMP_LT_U32:
		return "v_cmp_lt_u32";
	case GCN_V_CMP_EQ_U32:
		return "v_cmp_eq_u32";
	case GCN_V_CMP_LE_U32:
		return "v_cmp_le_u32";
	case GCN_V_CMP_GT_U32:
		return "v_cmp_gt_u32";
	case GCN_V_CMP_NE_U32:
		return "v_cmp_ne_u32";
	case GCN_V_CMP_GE_U32:
		return "v_cmp_ge_u32";
	case GCN_V_CMP_TRU_U32:
		return "v_cmp_tru_u32";
	case GCN_V_CMPX_F_U32:
		return "v_cmpx_f_u32";
	case GCN_V_CMPX_LT_U32:
		return "v_cmpx_lt_u32";
	case GCN_V_CMPX_EQ_U32:
		return "v_cmpx_eq_u32";
	case GCN_V_CMPX_LE_U32:
		return "v_cmpx_le_u32";
	case GCN_V_CMPX_GT_U32:
		return "v_cmpx_gt_u32";
	case GCN_V_CMPX_NE_U32:
		return "v_cmpx_ne_u32";
	case GCN_V_CMPX_GE_U32:
		return "v_cmpx_ge_u32";
	case GCN_V_CMPX_TRU_U32:
		return "v_cmpx_tru_u32";
	case GCN_V_CMP_F_U64:
		return "v_cmp_f_u64";
	case GCN_V_CMP_LT_U64:
		return "v_cmp_lt_u64";
	case GCN_V_CMP_EQ_U64:
		return "v_cmp_eq_u64";
	case GCN_V_CMP_LE_U64:
		return "v_cmp_le_u64";
	case GCN_V_CMP_GT_U64:
		return "v_cmp_gt_u64";
	case GCN_V_CMP_NE_U64:
		return "v_cmp_ne_u64";
	case GCN_V_CMP_GE_U64:
		return "v_cmp_ge_u64";
	case GCN_V_CMP_TRU_U64:
		return "v_cmp_tru_u64";
	case GCN_V_CMPX_F_U64:
		return "v_cmpx_f_u64";
	case GCN_V_CMPX_LT_U64:
		return "v_cmpx_lt_u64";
	case GCN_V_CMPX_EQ_U64:
		return "v_cmpx_eq_u64";
	case GCN_V_CMPX_LE_U64:
		return "v_cmpx_le_u64";
	case GCN_V_CMPX_GT_U64:
		return "v_cmpx_gt_u64";
	case GCN_V_CMPX_NE_U64:
		return "v_cmpx_ne_u64";
	case GCN_V_CMPX_GE_U64:
		return "v_cmpx_ge_u64";
	case GCN_V_CMPX_TRU_U64:
		return "v_cmpx_tru_u64";
	default:
		return "Invalid opcode";
	}
}

const char* gcnStrExpTarget(GcnExpTarget target) {
	if (target <= GCN_EXP_TARGET_MRT_7) {
		static const char* fieldnames[] = {
		    "mrt_color0", "mrt_color1", "mrt_color2", "mrt_color3",
		    "mrt_color4", "mrt_color5", "mrt_color6", "mrt_color7",
		};

		const uint32_t index = target - GCN_EXP_TARGET_MRT_0;
		_Static_assert(
		    GCN_EXP_TARGET_MRT_7 - GCN_EXP_TARGET_MRT_0 <=
			uasize(fieldnames),
		    ""
		);
		return fieldnames[index];
	}
	if (target >= GCN_EXP_TARGET_POS_0 && target <= GCN_EXP_TARGET_POS_3) {
		static const char* fieldnames[] = {
		    "pos0", "pos1", "pos2", "pos3"
		};

		const uint32_t index = target - GCN_EXP_TARGET_POS_0;
		_Static_assert(
		    GCN_EXP_TARGET_POS_3 - GCN_EXP_TARGET_POS_0 <=
			uasize(fieldnames),
		    ""
		);
		return fieldnames[index];
	}
	if (target >= GCN_EXP_TARGET_PARAM_0 &&
	    target <= GCN_EXP_TARGET_PARAM_31) {
		static const char* fieldnames[] = {
		    "param0",  "param1",  "param2",  "param3",	"param4",
		    "param5",  "param6",  "param7",  "param8",	"param9",
		    "param10", "param11", "param12", "param13", "param14",
		    "param15", "param16", "param17", "param18", "param19",
		    "param20", "param21", "param22", "param23", "param24",
		    "param25", "param26", "param27", "param28", "param29",
		    "param30", "param31",
		};

		const uint32_t index = target - GCN_EXP_TARGET_PARAM_0;
		_Static_assert(
		    GCN_EXP_TARGET_PARAM_31 - GCN_EXP_TARGET_PARAM_0 <=
			uasize(fieldnames),
		    ""
		);
		return fieldnames[index];
	}

	switch (target) {
	case GCN_EXP_TARGET_Z:
		return "z";
	case GCN_EXP_TARGET_NULL:
		return "NULL";
	default:
		return NULL;
	}
}

const char* gcnStrResourceType(GcnResourceType res) {
	switch (res) {
	case GCN_RES_POINTER:
		return "Pointer";
	case GCN_RES_IMAGE:
		return "Image";
	case GCN_RES_BUFFER:
		return "Buffer";
	case GCN_RES_SAMPLER:
		return "Sampler";
	case GCN_RES_CODE:
		return "Code";
	default:
		return NULL;
	}
}
