#ifndef _GNM_ERROR_H_
#define _GNM_ERROR_H_

#include <stdint.h>
#include "gnm_types.h"

OPENGNM_EXTERN_C_BEGIN

/*
 * GNM error codes.
 * ORBIS_GNM_ERROR_* values match the Sony SDK and are returned by the
 * firmware driver. GNM_ERROR_* values are opengnm-internal.
 */
typedef enum {
	GNM_ERROR_OK = 0x0,

	/* Sony SDK submission errors */
	ORBIS_GNM_ERROR_SUBMISSION_FAILED_INVALID_ARGUMENT = (int)0x80d11000,
	ORBIS_GNM_ERROR_SUBMISSION_NOT_ENOUGH_RESOURCES = (int)0x80d11001,
	ORBIS_GNM_ERROR_SUBMISSION_AND_FLIP_FAILED_INVALID_COMMAND_BUFFER =
	    (int)0x80d11080,
	ORBIS_GNM_ERROR_SUBMISSION_AND_FLIP_FAILED_INVALID_QUEUE_FULL =
	    (int)0x80d11081,
	ORBIS_GNM_ERROR_SUBMISSION_AND_FLIP_FAILED_REQUEST_FAILED =
	    (int)0x80d11082,
	ORBIS_GNM_ERROR_SUBMISSION_FAILED_INTERNAL_ERROR = (int)0x80d110ff,

	/* Sony SDK validation warnings */
	ORBIS_GNM_ERROR_VALIDATION_WARNING = (int)0x80d12000,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_RWBUFFER_ROTYPE = (int)0x80d12001,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_BLENDING = (int)0x80d12002,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_DRAW_CU_MASK = (int)0x80d12003,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_MRT_SETUP = (int)0x80d12004,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_DEPTH_RT_SETUP = (int)0x80d12005,
	ORBIS_GNM_ERROR_VALIDATION_WARNING_PS_AND_MRT_FORMAT = (int)0x80d1200f,

	/* Sony SDK validation errors */
	ORBIS_GNM_ERROR_VALIDATION_ERROR = (int)0x80d13000,
	ORBIS_GNM_ERROR_VALIDATION_VSHARP = (int)0x80d13001,
	ORBIS_GNM_ERROR_VALIDATION_TSHARP = (int)0x80d13002,
	ORBIS_GNM_ERROR_VALIDATION_RESOURCE = (int)0x80d13003,
	ORBIS_GNM_ERROR_VALIDATION_TABLE_MEMORY = (int)0x80d13004,
	ORBIS_GNM_ERROR_VALIDATION_WRITE_EVENT_OP = (int)0x80d13005,
	ORBIS_GNM_ERROR_VALIDATION_INDEX_BUFFER = (int)0x80d13006,
	ORBIS_GNM_ERROR_VALIDATION_TESS_FACTOR_BUFFER = (int)0x80d13007,
	ORBIS_GNM_ERROR_VALIDATION_SCRATCH_RING = (int)0x80d13008,
	ORBIS_GNM_ERROR_VALIDATION_PRIMITIVE_TYPE = (int)0x80d13009,
	ORBIS_GNM_ERROR_VALIDATION_INDEX_SIZE = (int)0x80d1300a,
	ORBIS_GNM_ERROR_VALIDATION_INLINE_DRAW_SIZE = (int)0x80d1300b,
	ORBIS_GNM_ERROR_VALIDATION_NUM_INPUT_PATCHES = (int)0x80d1300c,
	ORBIS_GNM_ERROR_VALIDATION_GS_MODE = (int)0x80d1300d,
	ORBIS_GNM_ERROR_VALIDATION_SHADER_ADDRESS = (int)0x80d1300e,
	ORBIS_GNM_ERROR_VALIDATION_BORDER_COLOR_TABLE = (int)0x80d1300f,
	ORBIS_GNM_ERROR_VALIDATION_SSHARP = (int)0x80d13010,
	ORBIS_GNM_ERROR_VALIDATION_DISPATCH_DRAW = (int)0x80d13011,
	ORBIS_GNM_ERROR_VALIDATION_ACTIVE_SHADER_STAGE = (int)0x80d13012,
	ORBIS_GNM_ERROR_VALIDATION_DCB = (int)0x80d13013,
	ORBIS_GNM_ERROR_VALIDATION_MISMATCH_SHADER_STAGE = (int)0x80d13014,
	ORBIS_GNM_ERROR_VALIDATION_MRT_SETUP = (int)0x80d13015,
	ORBIS_GNM_ERROR_VALIDATION_BAD_OP_CODE = (int)0x80d13016,
	ORBIS_GNM_ERROR_VALIDATION_DEPTH_RT_SETUP = (int)0x80d13017,
	ORBIS_GNM_ERROR_VALIDATION_NUM_INSTANCES = (int)0x80d13018,
	ORBIS_GNM_ERROR_VALIDATION_SRT = (int)0x80d13019,
	ORBIS_GNM_ERROR_VALIDATION_INVALID_ARGUMENT = (int)0x80d13ffd,
	ORBIS_GNM_ERROR_VALIDATION_FAILED_INTERNAL_ERROR = (int)0x80d13ffe,
	ORBIS_GNM_ERROR_VALIDATION_NOT_ENABLED = (int)0x80d13fff,

	/* Sony SDK capture errors */
	ORBIS_GNM_ERROR_CAPTURE_FILE_IO = (int)0x80d15000,
	ORBIS_GNM_ERROR_CAPTURE_RAZOR_NOT_LOADED = (int)0x80d15001,
	ORBIS_GNM_ERROR_CAPTURE_NOTHING_TO_CAPTURE = (int)0x80d15002,
	ORBIS_GNM_ERROR_CAPTURE_FAILED_INTERNAL = (int)0x80d1500f,

	/* Sony SDK generic failure — returned by all stub functions on retail
	 * firmware (SDMA, debugger, profiler, resource registration, etc.)
	 * Same value as GNM_ERROR_INTERNAL_FAILURE. */
	ORBIS_GNM_ERROR_FAILURE = (int)0x8eee00ff,

	/* opengnm internal errors */
	GNM_ERROR_INVALID_ARGS = (int)0x8eee0001,
	GNM_ERROR_INTERNAL_FAILURE = (int)0x8eee00ff,
	GNM_ERROR_CMD_FAILED = (int)0xffffffff,

	GNM_ERROR_INVALID_ALIGNMENT = 1,
	GNM_ERROR_INVALID_STATE,
	GNM_ERROR_OVERFLOW,
	GNM_ERROR_UNDERFLOW,
	GNM_ERROR_UNSUPPORTED,
	GNM_ERROR_SEMANTIC_NOT_FOUND,
	GNM_ERROR_ASM_FAILED,
} GnmError;

const char* sceGnmStrError(GnmError err) PS4_SYSV_ABI;

typedef enum {
	GNM_MSGSEV_WARN = 0,
	GNM_MSGSEV_ERR = 1,
} GnmMessageSeverity;

typedef void (*GnmMessageHandlerFunc)(
    GnmMessageSeverity severity, const char* message, void* userdata
);

void sceGnmSetMessageHandler(GnmMessageHandlerFunc handlerfunc, void* userdata);
void sceGnmWriteMsg(GnmMessageSeverity sev, const char* msg);
void sceGnmWriteMsgf(GnmMessageSeverity sev, const char* fmt, ...);

OPENGNM_EXTERN_C_END

#endif /* _GNM_ERROR_H_ */
